### ISSUE TITLE
[FR] 导出应用程序列表

### ISSUE THREAD

**Issue by Pantyhose-X** [LibChecker/LibChecker#1036]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### 导出应用程序列表
您可以在安装新ROM、恢复出厂设置甚至使用新设备后恢复应用程序。您还可以
与您的朋友分享这些应用程序列表。

注意：这不会备份应用程序数据或应用程序本身。

### Solution / 解决方案

导出为Markdown 格式列表
包含 (包名、应用名称、版本号 )
可以选择生成Google play 或 f-droid 链接
https://play.google.com/store/apps/details?id= `com.absinthe.libchecker`
https://f-droid.org/packages/ `com.absinthe.libchecker`

例子
List made using [LibChecker](https://play.google.com/store/apps/details?id=com.absinthe.libchecker)
[LibChecker](https://play.google.com/store/apps/details?id=com.absinthe.libchecker) 2.4.3

**Comment by zhaobozhen** [comment]
Great idea, but this feature is a bit off from the main function of LibChecker. Maybe I'll consider making it a debugging feature.

**Comment by ghost** [comment]
你使用其他应用备份安装包 在新设备安装不兼容, 你还可以 通过包名 找到同一个应用 和 版本号, 最新版本应用不一定是最好用的。毕竟googleplay 相同名称的应用大多了。这是一个非常有用的功能请求

**Comment by ghost** [comment]
这是一个非常有用的功能

**Comment by zhaobozhen** [comment]
Hi, I have done this feature. Now you can install the latest CI version to try. Just type `/dumpAppsInfoTxt` or `/dumpAppsInfoMd` into apps list search bar, it will done work.

<img width="1898" alt="image" src="https://github.com/user-attachments/assets/a8b5f75c-53a0-4342-8a4f-ba955ac003e8">

**Comment by ghost** [comment]
CI version is not compatible with GrapheneOS on my pixel7 device.
