### ISSUE TITLE
云端规则版本显示问题

### ISSUE THREAD

**Issue by binx6** [LibChecker/LibChecker#1037]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

**一个小Bug，如下视频：**

https://github.com/LibChecker/LibChecker/assets/123862842/c17435e4-757f-4d34-8d66-5d6cfd32e1d2

### Expected behavior / 预期行为

unknown

### Actual behavior / 实际行为

unknown

### Steps to reproduce / 复现步骤

1.打开app（我测试的设备是Redmi K20 Pro）
2.设置项选择“**云端规则**”
3.点击“**重启以更新**”
4.待回到app后重复上述操作

### UI / OS

MIUI12.5.6

### Android Version / Android 版本

11

### Additional info / 额外信息

**在我的印象里似乎跟从前不太一样**
**以前是更新了后会显示相对应的版号**
**比如34→34**

**Comment by binx6** [comment]
@zhaobozhen

**Comment by zhaobozhen** [comment]
看起来是更新失败了，方便的话可以在应用列表搜索框输入 /debugmode 后抓一下 logcat

**Comment by cyb233** [comment]
我有一样的问题，而且好像多个版本之前就遇到过，有空了抓个看看

**Comment by cyb233** [comment]
@zhaobozhen 
这是通过Android Studio捕获的Logcat和对应同时所有操作的视频
可以看到重启前文本会变成34，但重启后恢复为32

PS：因为Github上传格式和大小受限，所以logcat增加了json后缀，分卷压缩增加了zip后缀，使用时需注意一下
[vivo-V2231A-Android-13_2024-01-01_002710.logcat.json](https://github.com/LibChecker/LibChecker/files/13801797/vivo-V2231A-Android-13_2024-01-01_002710.logcat.json)
[Screen_recording_20240101_002648.zip.001.zip](https://github.com/LibChecker/LibChecker/files/13801717/Screen_recording_20240101_002648.zip.001.zip)
[Screen_recording_20240101_002648.zip.002.zip](https://github.com/LibChecker/LibChecker/files/13801719/Screen_recording_20240101_002648.zip.002.zip)

**Comment by binx6** [comment]
> @zhaobozhen 
> 这是通过Android Studio捕获的Logcat和对应同时所有操作的视频
> 可以看到重启前文本会变成34，但重启后恢复为32
> 
> PS：因为Github上传格式和大小受限，所以logcat增加了json后缀，分卷压缩增加了zip后缀，使用时需注意一下
> 

**哥们如果方便的话要不再用这个**[LogFox](https://githubfast.com/F0x1d/LogFox)**也抓一份**

**Comment by cyb233** [comment]
有线连Android Studio捕获的Logcat我认为没有必要再使用其他工具进行捕获

**Comment by cyb233** [comment]
另外回复不要带我的文件链接，因为我会修改文件

**Comment by binx6** [comment]
刚试了下最新的CI版本，33 → 35，面板数据依旧如此，但实际是更新成功了（对比了下库详情的内容而得）

**Comment by Cuddly-Red-Fox** [comment]
存在一样的问题QAQ

**Comment by binx6** [comment]
**经测试，最新CI版本已成功修复！感谢作者🙏**
![IMG_20240612_081137.jpg](https://github.com/LibChecker/LibChecker/assets/123862842/3246d2b8-6e77-4ac9-9760-3f945cb9063f)

**Comment by Cuddly-Red-Fox** [comment]
@binx6 你好 我更新到了最新版本的CI版本，似乎问题依旧，云端规则更新后显示34→36版本号，但是重启更新后依旧显示34，另外如果方便的话可以提供一下你说的修复后的CI版apk吗？（设备Xiaomi 13 Pro）谢谢（邮箱3367286693@qq.com）
![Screenshot_2024-06-12-08-41-03-178_com absinthe libchecker](https://github.com/LibChecker/LibChecker/assets/42781095/5e78dce7-c861-42bf-bffe-95249dbfccd7)

![Screenshot_2024-06-12-08-40-58-729_com absinthe libchecker](https://github.com/LibChecker/LibChecker/assets/42781095/da8b8f3a-f6ff-4e06-9ffd-3508374e51b2)

**Comment by binx6** [comment]
> @binx6 你好 我更新到了最新版本的CI版本，似乎问题依旧，云端规则更新后显示34→36版本号，但是重启更新后依旧显示34，另外如果方便的话可以提供一下你说的修复后的CI版apk吗？（设备Xiaomi 13 Pro）谢谢（邮箱3367286693@qq.com）

一样的版本。考虑到像你这样的因素，我把议题又重新打开了😂

**Comment by Cuddly-Red-Fox** [comment]
啊 好吧😂😂，略显无奈，我似乎无法提取APP的bug日志？也可能是我不会操作？如果要电脑的话😂😂（麻烦），只能等后续更新了

**Comment by binx6** [comment]
> 啊 好吧😂😂，略显无奈，我似乎无法提取APP的bug日志？也可能是我不会操作？如果要电脑的话😂😂（麻烦），只能等后续更新了

如果你的原生库规则更进了最新收纳的规则那问题就不大，顶多就是这个面板不美观而已（小问题，强迫症的话我也没办法😂），你可以找最新收纳的规则和对应的应用对比一下，反之则是大问题。

**Comment by cyb233** [comment]
https://github.com/LibChecker/LibChecker/actions/runs/9469255646

Foss版本编译包(2.5.0.dev.eb12e945)，在我的环境下(VIVO IQOO NEO 7，Android 14)经测试(32 → 36)问题依然存在，未验证实际规则库数据是否更新

**Comment by binx6** [comment]
> Foss版本编译包(2.5.0.dev.eb12e945)，在我的环境下(VIVO IQOO NEO 7，Android 14)经测试(32 → 36)问题依然存在，未验证实际规则库数据是否更新

我用的是**Market**（可能只是顺手解决了我的设备所引发的问题吧）

**Comment by Cuddly-Red-Fox** [comment]
Market和Foss版本的(2.5.0.dev.eb12e945)刚刚都试着安装了，还是一样，没区别😂😂😂

**Comment by binx6** [comment]
> Market和Foss版本的(2.5.0.dev.eb12e945)刚刚都试着安装了，还是一样，没区别😂😂😂

等进一步修复，但可能不会那么快，作者比较忙，你看我这issue都六个月了才修

**Comment by asuszwbUbuntu** [comment]
呃我试着卸载了APP，然后重新安装，似乎问题看上去是解决了？不清楚，不知道后续如果有规则更新会不会再次出现这种问题，无法验证😂😂😂😂（当然我试过在不卸载原有APP的情况下直接覆盖安装更新Market和Foss版本的(2.5.0.dev.eb12e945是依旧存在这个问题的，直到我刚刚卸载后重装
![Uploading Screenshot_2024-06-12-09-24-58-808_com.absinthe.libchecker.jpg…]()
）

**Comment by qhy040404** [comment]
其实这个鬼东西修了好多次了（

> 但是一直都有问题（

**Comment by Cuddly-Red-Fox** [comment]
呃我试着卸载了APP，然后重新安装，似乎问题看上去解决了？简而言之，不知道后续如果有规则更新会不会再次出现这种问题，无法验证😂😂😂（当然我试过在不卸载原有APP的情况下直接覆盖安装更新Market和Foss版本(2.5.0.dev.eb12e945仍然存在这方面，直到我刚刚卸载后重装 ）
![Screenshot_2024-06-12-09-24-58-808_com absinthe libchecker](https://github.com/LibChecker/LibChecker/assets/42781095/4e8c6571-59d2-4a41-84e6-4389f8dc5c3e)

**Comment by binx6** [comment]
> Foss版本编译包(2.5.0.dev.eb12e945)，在我的环境下(VIVO IQOO NEO 7，Android 14)经测试(32 → 36)问题依然存在，未验证实际规则库数据是否更新

尝试卸载重装看看，另一位也解决了

**Comment by cyb233** [comment]
我怀疑是否是因为在较旧版本存在bug影响到后续版本
我做了如下测试：
1. 我以往从未卸载过的状态，应用版本2.4.4，规则版本是32，在最新release和CI下均无法更新版本数字，依然显示32
2. 我卸载应用，安装了release(2.4.4)，此时规则版本为34，安装CI后随打包版本直接变为36
3. 此时我意识到问题，即原本我的2.4.4为什么规则库版本显示32，随后我重装2.4.4，更新版本34到36成功

根据以上测试分析，很可能是旧版本存在问题导致后续版本无法正常显示版本号
建议考虑重装

@zhaobozhen 大佬如果有空能复盘出真正原因是啥不？

**Comment by qhy040404** [comment]
> 安装CI后直接变为36

安装CI变为36是因为随应用打包的规则更新到36了

**Comment by cyb233** [comment]
> > 安装CI后直接变为36
> 
> 安装CI变为36是因为随应用打包的规则更新到36了

但是原本存在问题时，我安装CI依然显示32

**Comment by binx6** [comment]
> > 安装CI后直接变为36
> 
> 安装CI变为36是因为随应用打包的规则更新到36了

那我应该是真的解决了，毕竟我一贯是覆盖安装的😂这次覆盖安装都成功了极大概率不会再出Bug（对我而言）

**Comment by Cuddly-Red-Fox** [comment]
> 我怀疑是否是因为在较旧版本存在bug影响到后续版本 我做了如下测试：
> 
> 1. 我以往从未卸载过的状态，应用版本2.4.4，规则版本是32，在最新release和CI下均无法更新版本数字，依然显示32
> 2. 我卸载应用，安装了release(2.4.4)，此时规则版本为34，安装CI后随打包版本直接变为36
> 3. 此时我意识到问题，即原本我的2.4.4为什么规则库版本显示32，随后我重装2.4.4，更新版本34到36成功
> 
> 根据以上测试分析，很可能是旧版本存在问题导致后续版本无法正常显示版本号 建议考虑重装
> 
> @zhaobozhen 大佬如果有空能复盘出真正原因是啥不？

我抱有一样的看法😂😂😄

**Comment by Cuddly-Red-Fox** [comment]
> > > 安装CI后直接变为36
> > 
> > 
> > 安装CI变为36是因为随应用打包的规则更新到36了
> 
> 那我应该是真的解决了，毕竟我一贯是覆盖安装的😂这次覆盖安装都成功了极大概率不会再出Bug（对我而言）

我也一样，之前一直是覆盖更新

**Comment by binx6** [comment]
> > > > 安装CI后直接变为36
> > > 
> > > 
> > > 安装CI变为36是因为随应用打包的规则更新到36了
> > 
> > 那我应该是真的解决了，毕竟我一贯是覆盖安装的😂这次覆盖安装都成功了极大概率不会再出Bug（对我而言）
> 
> 我也一样，之前一直是覆盖更新

不一样，我没卸载哦

**Comment by Cuddly-Red-Fox** [comment]
呃 也对😂😂✓

**Comment by cyb233** [comment]
> 不一样，我没卸载哦

不排除你最后一次重装比我们晚的可能性😂导致更久远版本的问题在你这不存在

我至少从第一次回复时的版本就显示为32了😂

**Comment by cyb233** [comment]
> 刚试了下最新的CI版本，33 → 35，面板数据依旧如此，但实际是更新成功了（对比了下库详情的内容而得）

你这里应该是重装过，库版本比我新了，由此我认为在打包规则版本32~33之间修改的某个问题让后续修复覆盖更新成为可能

**Comment by binx6** [comment]
> 你这里应该是重装过，库版本比我新了，由此我认为在打包规则版本32~33之间修改的某个问题让后续修复覆盖更新成为可能

一直是覆盖安装的，最初提交的时候是33→34，你可以看我最初提交时的视频，如果还能看的话。3个月前是33→35，现在是36→36（已修复）。你提交的时候就是32所以是32有关的问题，而我是33，32如果我没记错的话当时对我而言是没问题的（当然现在也不想再回去测试了😂），等看作者怎么说吧

**Comment by zhaobozhen** [comment]
这个问题 qhy 解决了，我的开发环境一直在卸载重装，所以没有触发这个场景🙁
