### ISSUE TITLE
[BUG] 快照里少了两个软件

### ISSUE THREAD

**Issue by Doddddd** [LibChecker/LibChecker#1038]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

![Screenshot_20231204-221926_Trebuchet](https://github.com/LibChecker/LibChecker/assets/88972478/d1bf5851-9ce1-489c-8c4e-8079d0f1fef3)
<img width="798" alt="image" src="https://github.com/LibChecker/LibChecker/assets/88972478/a923bb1c-2437-47d6-9a3b-3f3e0afaf7da">
<img width="767" alt="image" src="https://github.com/LibChecker/LibChecker/assets/88972478/d2ffef04-e34c-4ceb-910c-1a35843dc41b">

### Expected behavior / 预期行为

325/325

### Actual behavior / 实际行为

323/325

### UI / OS

LineageOS 13

### Android Version / Android 版本

13

**Comment by zhaobozhen** [comment]
Fixed in d0ada143c13df5acf867f4510eee21b3479358be
