### ISSUE TITLE
[BUG] 几个 UI 问题

### ISSUE THREAD

**Issue by aidan24771** [LibChecker/LibChecker#1043]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

1. 如下视频，App Bundles 弹出界面内容超过一屏后，状态栏和底部 UI 闪烁。

https://github.com/LibChecker/LibChecker/assets/100205532/61bab95e-e95e-4e73-920d-329abdecfeaa

2. 如下视频，新打开应用，统计界面原生库跳转定位问题。

https://github.com/LibChecker/LibChecker/assets/100205532/e6f3a9aa-9b62-486b-a081-074cec387533

3. 如下图，同统计界面，斜体字显示不完整（“未标记的库”的“库”字），自测旧版无此问题（2.3.9(1587)，仅测试了该版本）。
![Screenshot_1](https://github.com/LibChecker/LibChecker/assets/100205532/c763e85b-e17b-41e5-9949-63840bb5fc4b)

4. 如下图，高级菜单弹出界面滑到底，底部线条不消失（我理解底部线条作用是提示底下还有内容）。
![Screenshot_2](https://github.com/LibChecker/LibChecker/assets/100205532/12a66126-ba1f-4dd0-83b4-5b0affa6024d)

5. 如下图，图表界面纵向放大，图表数字未及时消失（底部0.40%越过横轴，与4.00%干涉，且被底部手势指示条切去下半部分），最好使纵向放大时，上部和下部超出界限的图表数字及时消失，API 等级与其百分比同时消失（现在不是同步）。
![Screenshot_3](https://github.com/LibChecker/LibChecker/assets/100205532/466ac284-470e-4108-8635-b9e8bd4879c4)

### Expected behavior / 预期行为

详见描述

### Actual behavior / 实际行为

详见描述

### Steps to reproduce / 复现步骤

详见描述

### UI / OS

ColorOS 13.1

### Android Version / Android 版本

13

### Additional info / 额外信息

很喜欢这个软件，功能完备，UI 美观，强迫症有点受不了这几个细节问题，望改正。
P.S. Bug 描述中，问题1、4、5中都涉及到适配手势指示条，目前有的界面在手势指示条上有一条灰线，提示用户下面还有内容，而有的界面如 APP 的组件界面没有这条线。请问是否考虑统一一下？抑或由于 Android 有触底反馈，考虑取消这条线？只是提个建议请开发者考虑。

**Comment by aidan24771** [comment]
刚看到 Issues #559，问题似乎相似。

**Comment by zhaobozhen** [comment]
第四个问题，滑到列表最底部是会隐藏提示线的，从截图看底部最后一个按钮的 margin，应该是还没滑到底

**Comment by zhaobozhen** [comment]
第五个问题我使用的是图表组件，所以无法修改，可以去 https://github.com/AppDevNext/AndroidChart 提 issue

**Comment by Jesse205** [comment]
第一个我觉得是一个bug吧

**Comment by zhaobozhen** [comment]
> 第一个我觉得是一个bug吧

第一个问题已经修复了
