### ISSUE TITLE
[FR] Add react-native-vision-camera detection

### ISSUE THREAD

**Issue by mrousavy** [LibChecker/LibChecker#1046]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

LibChecker already detects React Native specific libraries such as react-native-skia and react-native-reanimated.

Since Cameras are quite complex and differ a lot in their implementation, it would be pretty cool to also detect [react-native-vision-camera](https://github.com/mrousavy/react-native-vision-camera), which is the defacto go-to Camera library for React Native.

e.g. Discord uses it.

<img src="https://github.com/LibChecker/LibChecker/assets/15199031/a1c4deb5-f598-408b-a653-504dd042fda9" width="35%" />

Thanks!

**Comment by qhy040404** [comment]
submit the rule [here](https://github.com/LibChecker/LibChecker-Rules)
