### ISSUE TITLE
[BUG] need 2x open for it to refreh

### ISSUE THREAD

**Issue by researchscum** [LibChecker/LibChecker#1050]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

in 2.4.2 if i open it and there are new app updated or installed it will refresh directly but since 2.4.3 when i open it, it will not refresh directly, i need to close the app first and then open it again.

### Expected behavior / 预期行为

directly refresh it.

### Actual behavior / 实际行为

not refreshed need to close the app first the re-open it.

### Steps to reproduce / 复现步骤

1. set the first tab of app to updated time
2. close the app
3. remove the app from recent or force stop it
5. install new update of an app or install new app
6. open libchecker (the top of the list bot the newly update or installed app)
7. close it and re-open.

### UI / OS

MIUI

### Android Version / Android 版本

13

### Additional info / 额外信息

in 2.4.2 it refreshed when i open it but since 2.4.3 it need to be closed (press back button) and then press open the app again before it can update list of app.

**Comment by zhaobozhen** [comment]
Hey, is this issue existing in 2.4.4 or laterst CI?

**Comment by researchscum** [comment]
it happen when play store still 2.4.2 then i update to 2.4.4 FOSS from here, but now from play store already 2.4.4 so i uninstalled it and install one from play store and the issue gone.
