### ISSUE TITLE
[FR] Highlighting launcher activities

### ISSUE THREAD

**Issue by Goooler** [LibChecker/LibChecker#1075]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

Highlight the main activities (marked with `android.intent.category.LAUNCHER`) in an app.

**Comment by qhy040404** [comment]
Currently, the one that jumps from the statistics page to details is highlighted, and the exported components are highlighted with fonts. There seems to be no more prompt method.

**Comment by zhaobozhen** [comment]
I designed an alternative interaction method to fulfill this feature request. Just long-press the `Launch` button.

![Screenshot_20240702_225212](https://github.com/LibChecker/LibChecker/assets/25247117/563e9b4f-203f-4a01-8b92-c05115602bab)
