### ISSUE TITLE
[FR] 既然国内的市场也不上线了，是否本项目要加入App内检查更新和App内下载apk并进行安装呢？

### ISSUE THREAD

**Issue by liyuhaolol** [LibChecker/LibChecker#1086]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

毕竟没了国内直接检查更新的渠道，谁能老跑到外网检查这个问题。除了GooglePlay渠道以外的apk，完全可以加入App内升级，来保证App的版本吧？纯建议而已。

**Comment by zhaobozhen** [comment]
或许可以在 foss 版本加一个检查更新的功能？商店版应用市场本身会推送更新，而且加入应用内更新可能导致 Google Play 不能过审。

**Comment by su1216** [comment]
> 或许可以在 foss 版本加一个检查更新的功能？商店版应用市场本身会推送更新，而且加入应用内更新可能导致 Google Play 不能过审。

分渠道打包

**Comment by binx6** [comment]
**像这种三天两头就有CI版本的应用你总去检查更新不会觉得频繁？只考虑正式版当我没说**

**Comment by binx6** [comment]
**像这种三天两头就有CI版本的应用你总去检查更新不会觉得频繁？只考虑正式版当我没说**

**Comment by binx6** [comment]
> **像这种三天两头就有CI版本的应用你总去检查更新不会觉得频繁？只考虑正式版当我没说**

@zhaobozhen 
**我觉得这个**[蒲公英](https://www.pgyer.com/)**平台值得考虑一下**

**Comment by liyuhaolol** [comment]
> **像这种三天两头就有CI版本的应用你总去检查更新不会觉得频繁？只考虑正式版当我没说**

不会啊，检查版本更新也可以用小红点提醒，不喜欢更新就不更，不影响用户使用的。手机厂商内测应用的时候也是三天两头的更新也没谁说频繁啥的。金丝雀版本的Edge，微软最快半天更新了一次。你自己装的就是个更新频率高的版本，更新快自己心里也得有谱吧。

**Comment by binx6** [comment]
> 不会啊，检查版本更新也可以用小红点提醒，不喜欢更新就不更，不影响用户使用的。手机厂商内测应用的时候也是三天两头的更新也没谁说频繁啥的。金丝雀版本的Edge，微软最快半天更新了一次。你自己装的就是个更新频率高的版本，更新快自己心里也得有谱吧。

虽然不怎么赞同你的观点，但也并非不可

**Comment by Goooler** [comment]
在 Foss 变种上启动时直接检查 Github Releases 是否有更新就是了，有更新引导用户跳转到网页上下载安装

**Comment by Nostalgia-WZQ** [comment]
可以用f-droid

**Comment by IlIllIl** [comment]
可以自带检查更新（手动触发），不喜欢自带弹窗/小红点的更新提示

**Comment by kkoshin** [comment]
原版 F-Droid 客户端可能有点丑，可以试下社区的版本，比如：https://github.com/kitsunyan/foxy-droid

个人觉得有一个统一的应用商店体验应该是最好的，事实上也已经有了（Google Play 和 F-Droid），应用内更新没太必要。

可能国情不同，一些用户确实没有使用应用商店的习惯。

**Comment by Jesse205** [comment]
应用内不是已经有了“获取更新”功能吗，我觉得只提供更新渠道就足够了，没必要实际地检查更新。

如果真的要检查更新，应用商店F-Droid就可以。而且不仅可以检查这一个APP。但是F-Droid只能下载开源版本，无法下载市场版本。

如果要在国内下载新版本的话，加一个国内的网盘就行。前面说的“蒲公英”应该也行

**Comment by dylanleesky** [comment]
> 可以自带检查更新（手动触发），不喜欢自带弹窗/小红点的更新提示

对，强迫症实在受不了忽然多出来个+1或者小红点。或者显示几天自动消除也能接受。
