### ISSUE TITLE
[BUG] Xposed 模块页面无法上下滑动

### ISSUE THREAD

**Issue by IlIllIl** [LibChecker/LibChecker#1094]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest CI / 最新 CI 版

### Bug description / Bug 描述

![853869E0-39E3-412A-B457-FFB0E308B8BB](https://github.com/LibChecker/LibChecker/assets/99599914/61c2d278-895d-43f6-b7c7-f579950c262b)
![F92647F2-B6E5-4BE4-883C-2CB5CE147F66](https://github.com/LibChecker/LibChecker/assets/99599914/49d46e6f-06b7-4698-845c-4289c38ad82f)

### Expected behavior / 预期行为

正常滑动查看

### Actual behavior / 实际行为

滑不动

### UI / OS

HyperOS

### Android Version / Android 版本

13

**Comment by binx6** [comment]
**这并不是bug，而是本来就没有写，库详情也是这样** => [#884](https://github.com/LibChecker/LibChecker/discussions/884)

**Comment by IlIllIl** [comment]
> **这并不是bug，而是本来就没有写，库详情也是这样** => [#884](https://github.com/LibChecker/LibChecker/discussions/884)

@zhaobozhen 库详情也建议修一下吧，LC这套UX我非常喜欢，希望能更丝滑一点🌸

**Comment by binx6** [comment]
@IlIllIl 最新CI版本已修复，#1165
