### ISSUE TITLE
[BUG] AESEncryptionHelper中这段代码是不是有问题

### ISSUE THREAD

**Issue by JoeVX** [LibChecker/LibChecker#1097]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

![image](https://github.com/LibChecker/LibChecker/assets/25249779/245f0f31-9c1f-428d-a2c6-adb38bb44de8)

### Expected behavior / 预期行为

第一行已经读取到了字节数组,后边的有什么用呢

### Actual behavior / 实际行为

.

### UI / OS

.

### Android Version / Android 版本

.

**Comment by qhy040404** [comment]
pr welcome

**Comment by zhaobozhen** [comment]
好像是没有什么用
