### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by binx6** [LibChecker/LibChecker#1133]
### Checklist / 检查清单

- [x] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest CI / 最新 CI 版

### Bug description / Bug 描述

1. 上次是做了Xposed模块页面的滑动，但是在我的设备上有闪烁问题（状态栏和底部小白条这两个地方），可能是md3组件的问题，不知道是不是因为重叠而致
2. 搜索大写“QQ”后再点进去查看瞬间LibChecker秒Crash

### Expected behavior / 预期行为

影响体验感

### Actual behavior / 实际行为

unknown

### Steps to reproduce / 复现步骤

设备：Redmi K20 Pro
问题一复现：查看Scene这款应用的xp模块页面就会导致这样
问题二复现：🔍QQ并点进去查看，重复此操作
不保证都能完全稳定的复现，第一个基本上能

### UI / OS

MIUI 12.5.6

### Android Version / Android 版本

11

### Additional info / 额外信息

暂时不大方便获取日志，耽搁修复进度了
Ps：我认为md3组件的问题是主因

**Comment by binx6** [comment]
@zhaobozhen

**Comment by binx6** [comment]
**插个题外话，我觉得有必要做一个UncaughtExceptionHandler，出错了和日志一起显示在应用页面内，然后可以用Handler配合Looper兜住，保证起码发生错误了不会直接闪退（除非类似ANR或者Native崩溃那种严重问题），这样也便于及时的反馈，参考下这个[仓库](https://github.com/yongfengnice/NeverJavaCrash)**

**Comment by binx6** [comment]
> **插个题外话，我觉得有必要做一个UncaughtExceptionHandler，出错了和日志一起显示在应用页面内，然后可以用Handler配合Looper兜住，保证起码发生错误了不会直接闪退（除非类似ANR或者Native崩溃那种严重问题），这样也便于及时的反馈，参考下这个[仓库](https://github.com/yongfengnice/NeverJavaCrash)**

问题一复现视频↓
https://github.com/LibChecker/LibChecker/assets/123862842/b22b14b2-6bb8-42e8-83c2-016cae8cb2fc

**Comment by zhaobozhen** [comment]
> **插个题外话，我觉得有必要做一个UncaughtExceptionHandler，出错了和日志一起显示在应用页面内，然后可以用Handler配合Looper兜住，保证起码发生错误了不会直接闪退（除非类似ANR或者Native崩溃那种严重问题），这样也便于及时的反馈，参考下这个[仓库](https://github.com/yongfengnice/NeverJavaCrash)**

现在有类似的机制，但是是根据堆栈信息来选择是否崩溃的。我觉得有些情况是需要允许应用崩溃重启的，可以避免出现更多未知的问题

**Comment by binx6** [comment]
问题二复现视频↓
https://github.com/LibChecker/LibChecker/assets/123862842/f1d71813-903f-4361-b39a-a430ccd8cbd9

**Comment by binx6** [comment]
> 现在有类似的机制，但是是根据堆栈信息来选择是否崩溃的。我觉得有些情况是需要允许应用崩溃重启的，可以避免出现更多未知的问题

有个折中的方案，让用户手动选择重启或者上传，如果觉得还是不大行就算了😂

**Comment by binx6** [comment]
补充一条：目前我遇到了其它的搜索崩溃问题，有些是在搜索时，还有一些是在搜索完并点击时，且均不能稳定复现，也可能页面切换过快来不及刷新而致？

**Comment by binx6** [comment]
> 现在

**问题一已得到解决👍，问题二依旧存在**，#1155
