### ISSUE TITLE
如果没有32位应用就不用展示0.0.%了吧

### ISSUE THREAD

**Issue by lvzhenbo** [LibChecker/LibChecker#1162]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

在饼盘里不用展示已经为0的数据，可以简化界面

### Solution / 解决方案

不用展示

### Additional info / 额外信息

![Screenshot_2024-03-18-01-02-44-535_com absinthe libchecker](https://github.com/LibChecker/LibChecker/assets/32427677/84f54073-ec1a-494e-9f9e-49b7b052fb88)

**Comment by zhaobozhen** [comment]
或许可以增加一个开关来控制

**Comment by zhaobozhen** [comment]
表格统计应该列出所有的 x 值，这样用户才能清楚完整的统计范围。因此这个需求暂不实现。
