### ISSUE TITLE
[BUG] 无法查看没有签名的APK的信息

### ISSUE THREAD

**Issue by Rw-Ro** [LibChecker/LibChecker#1173]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

用libchecker打开一个没有正确签名的APK，无法查看。

### Expected behavior / 预期行为

打开详情页

### Actual behavior / 实际行为

退出

### Steps to reproduce / 复现步骤

用libchecker打开一个没有正确签名的APK文件

### UI / OS

MIUI

### Android Version / Android 版本

12

**Comment by zhaobozhen** [comment]
现在应用完全使用 PackageManager 的接口解析 APK，在解析没有正确签名的 APK 时，会无法通过 PackageParser 中的签名校验，导致解析失败

**Comment by Rw-Ro** [comment]
要解决这个问题，就要换一个接口。
你打算怎么做？

**Comment by zhaobozhen** [comment]
> 要解决这个问题，就要换一个接口。
> 
> 你打算怎么做？

我会先看下有没有绕过签名校验的方法，如果你有其他线索也欢迎提供

**Comment by su1216** [comment]
能否提供个apk文件

**Comment by zhaobozhen** [comment]
我之前忘记了，这个问题已经被 #1081 解决了，可以使用最新的 CI 版本验证。
https://t.me/libchecker_ci/1861
