### ISSUE TITLE
[BUG] 移除重复的dex包名

### ISSUE THREAD

**Issue by Kyant0** [LibChecker/LibChecker#1174]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

![Screenshot_20240403-131112](https://github.com/LibChecker/LibChecker/assets/76829190/b17b434c-0cd8-454f-a549-ab1154c1ca86)

如果是多dex，可能会有重复的类名

### Expected behavior / 预期行为

只显示一次

### Actual behavior / 实际行为

可能会显示多次

### UI / OS

Pixel

### Android Version / Android 版本

13

### Additional info / 额外信息

distinct 一下

**Comment by zhaobozhen** [comment]
代码上应该是有去重的，可以提供下测试的 APK 吗？

**Comment by Kyant0** [comment]
[Uploading HarMusic_2024.001.0-release.zip…]()

**Comment by Kyant0** [comment]
[HarMusic_2024.001.0-release.zip](https://github.com/LibChecker/LibChecker/files/14920993/HarMusic_2024.001.0-release.zip)
