### ISSUE TITLE
[FR] 根据应用程序的ABI制作ABI图表

### ISSUE THREAD

**Issue by Rw-Ro** [LibChecker/LibChecker#1175]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

使ABI图表显示的信息更清晰

### Solution / 解决方案

统计每一种ABI，而不是把不同的ABI分为32位和64位然后统计。例如一个ABI图表有这些内容：无原生库、arm64-v8a、armeabi-v7a、armeabi、x86_64、x86

### Additional info / 额外信息

armeabi-v7a与armeabi这两个不同的ABI都是32位的……

**Comment by zhaobozhen** [comment]
或许可以增加一个开关来控制
