### ISSUE TITLE
[BUG] 快捷启动图表闪退

### ISSUE THREAD

**Issue by ZXAS007** [LibChecker/LibChecker#1191]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest CI / 最新 CI 版

### Bug description / Bug 描述

长按桌面图标厚的图表选项，启动应用会闪退

### Expected behavior / 预期行为

正常打开应用图表功能页面

### Actual behavior / 实际行为

应用闪退

### Steps to reproduce / 复现步骤

和bug描述一样的行为

### UI / OS

澎湃OS1.0.24.4.16.DEV

### Android Version / Android 版本

14

### Additional info / 额外信息

这个不是必现bug，可能会有一两次正常启动功能
下图是应用闪退时系统提供的错误报告，2.5.0.dev.2c 3ffc06版本
![Screenshot_2024-04-22-23-13-48-018_com miui bugreport](https://github.com/LibChecker/LibChecker/assets/69531154/aba3c975-bd7a-4297-81ea-cba22d5c2c74)

**Comment by binx6** [comment]
同遇，不过我这必现，单击“图表”就闪
