### ISSUE TITLE
[FR] 支持识别mips、mips64架构

### ISSUE THREAD

**Issue by binx6** [LibChecker/LibChecker#1202]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

起因是用其它更专业的工具看`AIDA64`这款应用所采用的技术，顺带看到的架构。后来查阅了下相关资料，这个架构虽然少见，但感觉还是做下识别比较好

### Solution / 解决方案

修改项目结构中的类和XML

### Additional info / 额外信息

**相关参考**
1. [AIDA64](https://www.aida64.com/downloads)
2. [词条](https://baike.baidu.com/item/MIPS架构/1539401?fr=ge_ala)

**Comment by binx6** [comment]
@zhaobozhen

**Comment by zhaobozhen** [comment]
后面有时间我加一下
