### ISSUE TITLE
[FR] 针对加固后的 APK 判断是否存在 Compose 放宽限制

### ISSUE THREAD

**Issue by oOJohn6Oo** [LibChecker/LibChecker#1260]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

爱加密加固后，不脱壳的情况下，获取不到 APK 使用的类信息，但 META-INF 中实际上可以检测到对应的版本信息。
这种情况下 APK 大概率是使用了 Compose 的。

### Solution / 解决方案

检测到 APK 被加固并且 META-INF 中存在对应版本信息，`AppDetailActivity` 可以显示 `Compose` 的图标并显示具体版本。

### Additional info / 额外信息

看源码中检测是否使用 Kotlin 其实也就是判断了几个文件是否存在，没有扫描具体类信息。所以感觉 Compose 也可以放开。

**Comment by zhaobozhen** [comment]
https://github.com/LibChecker/LibChecker/blob/067fee5026fdb0944a23cc6be6c3b9d8aa869835/app/src/main/kotlin/com/absinthe/libchecker/utils/extensions/PackageInfoExtensions.kt#L369

现在就有通过 META-INF 判断，如果有判断不准确的实例可以提供一下

**Comment by oOJohn6Oo** [comment]
Oh, 那确实是特例了，我尝试的APP 是 [QuizAI](https://play.google.com/store/apps/details?id=com.intsig.camexam)，列表里的都能看见Compose 的预览 Activity，获取 base.apk 也能看见Compose 的版本信息。

**Comment by oOJohn6Oo** [comment]
@zhaobozhen    感谢关注，修复速度非常快，👍。但... #1261 其实不太推荐。

1.  判断这个`PreviewActivity`存在，逻辑上可行，但其实理论上它不应该在 Release APK 中存在的，可以看[这个 issue](https://issuetracker.google.com/issues/190649014)，还有[官方的教程](https://developer.android.com/develop/ui/compose/setup?hl=zh-cn)，都是推荐使用 `debugImplementation 'androidx.compose.ui:ui-tooling'`。

2. 至于为什么有 version 文件检测不到 Compose 的具体原因，我上午跑了下 Demo，应该是 `entry.name`包含`META-INF/`导致的，可以看下面这个图。
但是因为其他 APP 检测是正常的，所以我也没太深入研究，所以没好意思提 PR，建议可以将
```
entry.isDirectory.not() &&
            entry.name.startsWith("androidx.compose") &&
            entry.name.endsWith(".version")
```
替换为：
```
entry.isDirectory.not() &&
            (entry.name.startsWith("androidx.compose") || entry.name.startsWith("META-INF/androidx.compose")) &&
            entry.name.endsWith(".version")
```

<img width="1080" alt="Xnip2024-07-01_11-19-13" src="https://github.com/LibChecker/LibChecker/assets/24718357/a148c742-3f25-40e3-8033-2d3772bd7903">

**Comment by zhaobozhen** [comment]
感谢提供建议，确实这样会更完善一点，晚点时候我会看看❤️

**Comment by oOJohn6Oo** [comment]
> 感谢提供建议，确实这样会更完善一点，晚点时候我会看看❤️

不用客气，还想请问一下现在版本发布是中断了吗？修复完成后我在哪可以下载到最新 APK？

**Comment by zhaobozhen** [comment]
> > 感谢提供建议，确实这样会更完善一点，晚点时候我会看看❤️
> 
> 不用客气，还想请问一下现在版本发布是中断了吗？修复完成后我在哪可以下载到最新 APK？

下一个版本还有一些关键功能没有完成，还需要一些时间。如果你使用 Telegram，可以在 [@libchecker_ci](https://t.me/libchecker_ci) 获取最新版本，或者在 GitHub Action 中自己下载产物
