### ISSUE TITLE
[FR]检查原生库是否可以直接加载

### ISSUE THREAD

**Issue by jimstar06** [LibChecker/LibChecker#127]
Android 6.0开始，若原生库未压缩且对齐4KB边界，系统无需在安装时解压原生库而是通过mmap直接从apk中加载，对于包含大量原生库的单ABI APP，可有效减少安装体积。

Native Libs Monitor可以检查原生库是否直接加载，但该APP已经没有维护了。
[Native Libs Monitor](https://play.google.com/store/apps/details?id=com.xh.nativelibsmonitor.app)

FR: 若原生库可以直接加载，在详情页增加显示标志。

[Android Studio Ref.](https://developer.android.com/topic/performance/reduce-apk-size#extract-false)
[StackOverflow Ref.](https://stackoverflow.com/questions/42998083/setting-androidextractnativelibs-false-to-reduce-app-size/47541129)

**Comment by zhaobozhen** [comment]
这个提议好耶

**Comment by zhaobozhen** [comment]
Supported.
