### ISSUE TITLE
快照界面的显示问题

### ISSUE THREAD

**Issue by ToukoYuko** [LibChecker/LibChecker#131]
![Screenshot_20210807-161242](https://user-images.githubusercontent.com/37900497/128593853-eb3415c1-b017-4640-9fda-ad91f28f2823.png)
快照界面在显示库详情时，相关框架宽度为设备宽度，而不包含库详情时，宽度略窄，如上图所示。但某些时候不包含库详情时，框架宽度也为设备宽度，如下图所示。
![Screenshot_20210807-161315](https://user-images.githubusercontent.com/37900497/128593906-1187706b-ed1c-4ce2-af6c-99f507e89feb.png)
不知道是不是我设备原因，导致的显示问题；
设备：sony xz2；
系统：Android10.

**Comment by zhaobozhen** [comment]
试一下 2.1.5 版本有无此问题

**Comment by ToukoYuko** [comment]
谷歌未推送版本2.1.5，我从[酷安](https://www.coolapk.com/apk/com.absinthe.libchecker)下载的相关安装包；
![Screenshot_20210808-144813](https://user-images.githubusercontent.com/37900497/128623589-42006b47-46ff-4d3e-a99b-9925c6f1e6ce.png)
![Screenshot_20210808-144840](https://user-images.githubusercontent.com/37900497/128623596-45cb690f-e09d-40c0-9cfa-c947e46974a5.png)
![Screenshot_20210808-144845](https://user-images.githubusercontent.com/37900497/128623650-bef65184-490a-4966-8861-ff63f390d680.png)
![Screenshot_20210808-144901](https://user-images.githubusercontent.com/37900497/128623683-107281a7-4471-48b1-a942-231c26a2d8b3.png)

**Comment by zhaobozhen** [comment]
> 谷歌未推送版本2.1.5，我从[酷安](https://www.coolapk.com/apk/com.absinthe.libchecker)下载的相关安装包；
> ![Screenshot_20210808-144813](https://user-images.githubusercontent.com/37900497/128623589-42006b47-46ff-4d3e-a99b-9925c6f1e6ce.png)
> ![Screenshot_20210808-144840](https://user-images.githubusercontent.com/37900497/128623596-45cb690f-e09d-40c0-9cfa-c947e46974a5.png)
> ![Screenshot_20210808-144845](https://user-images.githubusercontent.com/37900497/128623650-bef65184-490a-4966-8861-ff63f390d680.png)
> ![Screenshot_20210808-144901](https://user-images.githubusercontent.com/37900497/128623683-107281a7-4471-48b1-a942-231c26a2d8b3.png)
> 

只有这个页面有问题吗？其他页面呢？

**Comment by ToukoYuko** [comment]
![Screenshot_20210809-182522](https://user-images.githubusercontent.com/37900497/128692805-3bbdafb6-20ac-4af7-9a61-6a62fad943e6.png)
![Screenshot_20210809-182722](https://user-images.githubusercontent.com/37900497/128692977-9b8fa010-6ccb-43cc-b0c1-90ed0451678b.png)

还有Pixiv和tg，我不知道这两个软件显示是否正确；其他的软件更新没有更新组件，相关页面为空白。
![Screenshot_20210809-182828](https://user-images.githubusercontent.com/37900497/128693120-a22b8694-566c-4451-96c6-f64fe689fe96.png)

**Comment by zhaobozhen** [comment]
我是想问，除了快照这个页面，其他页面还有不正常的情况吗

**Comment by ToukoYuko** [comment]
额，是我理解不到位，其他页面没有这个问题

**Comment by zhaobozhen** [comment]
为啥关了，我还没解呢

**Comment by ToukoYuko** [comment]
哦

**Comment by ToukoYuko** [comment]
2.1.6版本，该问题基本修复了。

**Comment by zhaobozhen** [comment]
> 2.1.6版本，该问题基本修复了。

基本修复是指还有概率出现吗😂因为我的机器一直复现不到，我也不确定。

**Comment by ToukoYuko** [comment]
在我这边所有页面都没出现该问题了。

**Comment by ToukoYuko** [comment]
在我这边快照界面已经没有该问题了。其他界面也一切正常。

**Comment by zhaobozhen** [comment]
那我这边先关闭喽，有问题再重开此问题。
