### ISSUE TITLE
2.1.5显示bug

### ISSUE THREAD

**Issue by Soul-Traveler** [LibChecker/LibChecker#132]
2.1.5版本显示问题![Screenshot_20210808_085355_com.absinthe.libchecker.jpg](https://user-images.githubusercontent.com/87885288/128617392-32bcc67b-88b0-4167-a3db-98d0932caa88.jpg)https://user-images.githubusercontent.com/87885288/128617393-7de258e9-7b47-44b4-867a-fb381cdc91bc.mp4

**Comment by zhaobozhen** [comment]
点进去就这样吗

**Comment by Soul-Traveler** [comment]
单击鸿蒙软件的那个切换键会触发发自我的荣耀手机-------- 原始邮件 --------发件人： Absinthe ***@***.***>日期： 2021年8月8日周日 中午12:31收件人： zhaobozhen/LibChecker ***@***.***>抄送： Soul-Traveler ***@***.***>, Manual ***@***.***>主    题： Re: [zhaobozhen/LibChecker] 2.1.5显示bug (#132)

点进去就这样吗

**Comment by Soul-Traveler** [comment]
快速点击会导致闪退发自我的荣耀手机-------- 原始邮件 --------发件人： ***@***.***日期： 2021年8月8日周日 下午1:26收件人： zhaobozhen/LibChecker ***@***.***>主    题： 回复：[zhaobozhen/LibChecker] 2.1.5显示bug (#132)单击鸿蒙软件的那个切换键会触发发自我的荣耀手机-------- 原始邮件 --------发件人： Absinthe ***@***.***>日期： 2021年8月8日周日 中午12:31收件人： zhaobozhen/LibChecker ***@***.***>抄送： Soul-Traveler ***@***.***>, Manual ***@***.***>主    题： Re: [zhaobozhen/LibChecker] 2.1.5显示bug (#132)

点进去就这样吗
