### ISSUE TITLE
[BUG] 显示异常

### ISSUE THREAD

**Issue by Heimaojingzhang888** [LibChecker/LibChecker#1344]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [x] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

显示异常
![Screenshot_2024-09-07-09-59-48-685_com absinthe libchecker-edit](https://github.com/user-attachments/assets/27eba7ac-ae79-47d3-bf63-caa0275b8dc2)

### Expected behavior / 预期行为

修复

### Actual behavior / 实际行为

显示异常

### UI / OS

HyperOS

### Android Version / Android 版本

14

**Comment by zhaobozhen** [comment]
虽然很奇怪，但这就是最新的 material design 设计，并不是显示异常
