### ISSUE TITLE
Statistics error when accessing OPPO push software
Because the OPPO push service components used by many software developers (Pinduoduo, Alipay, etc.) are unofficial service components, the software mistakenly does not include such software in the statistics, causing users to think that the software is not included in OPPO push. I hope the developers will fix this problem.

### ISSUE THREAD

**Issue by Keepsmile31** [LibChecker/LibChecker#1373]
Because the OPPO push service components used by many software developers (Pinduoduo, Alipay, etc.) are unofficial service components, the software mistakenly does not include such software in the statistics, causing users to think that the software is not included in OPPO push. I hope the developers will fix this problem.

**Comment by zhaobozhen** [comment]
The marked rules only includes components declared by the official SDKs, and does not include information about components customized by third-party applications.This is because these custom components are untrustworthy and significantly increase the cost of maintaining the marked rules.
