### ISSUE TITLE
[FR] 数据库创建貌似没有实现双重检查锁定

### ISSUE THREAD

**Issue by JoeVX** [LibChecker/LibChecker#1382]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

![image](https://github.com/user-attachments/assets/c23b0e09-47a5-4e4f-8cc2-bb51171b4895)
这段代码在同步代码块中貌似没有进行二次检查

### Additional info / 额外信息

或者我太菜,没看懂

**Comment by zhaobozhen** [comment]
这个是早期 room 的 demo 代码写法，现在看来已经可以用 lazy 语法来简化。如果你有兴趣，可以提交一个 PR 来修改。
