### ISSUE TITLE
Trackers in the App

### ISSUE THREAD

**Issue by ghost** [LibChecker/LibChecker#1401]
Hey,

i use the App but I'm not happy about the 2 Trackers in the App from Microsoft. Look here: https://reports.exodus-privacy.eu.org/en/reports/com.absinthe.libchecker/latest/

And I use the Github Foss APK Version but I don't understand how a Foss App can have Trackers from Microsoft...I hope that you can remove both Trackers and I have a better Alternative which is leightweight and even Open Source. Look here: https://plausible.io/

I hope you can change that. I wanna use your App but the Trackers are holding me back from using it.

**Comment by zhaobozhen** [comment]
In the FOSS version, AppCenter is essentially an empty implementation, so there is no tracker-related code included. If you’re still concerned, you can download it from the F-Droid store.

See also:https://github.com/LibChecker/LibChecker/blob/master/app/src/foss/kotlin/com/microsoft/appcenter/AppCenter.java

**Comment by ghost** [comment]
Oh okay, thank you for telling. And thanks, but I don't trust the Main F-Droid Repo, because of their Security Issues. Look here: https://privsec.dev/posts/android/f-droid-security-issues/

**Comment by ghost** [comment]
@zhaobozhen I'm concerned how it would be, when it changes to Firebase. Could you not just remove both Trackers? Specially when it is empty. Or change to better Alternatives which do the same work, like plausible, which I mentioned before.
