### ISSUE TITLE
Pin Feature

### ISSUE THREAD

**Issue by ghost** [LibChecker/LibChecker#1402]
Hey,

i would love if Material Files would have the Option in the Settings to enable Pin to use the App. That every time I want to access the App, I need to type the Pin. It would make it more secure.

**Comment by zhaobozhen** [comment]
Sorry, I don’t understand what you mean. Could you please explain your requirements in more detail?

**Comment by ghost** [comment]
Pin Lock like if you lock your Phone and need to type a Pin to unlock. Same for the App. That I can enable Pin Lock in the Settings from the App, that the App locks immediately when I switch to other Apps, while it is opened or when I close it.

**Comment by zhaobozhen** [comment]
I understand, but I don’t think LibChecker needs this feature. The information displayed in the app doesn’t involve any private content; it’s all public. Therefore, I’m inclined not to add a pin lock feature.

**Comment by ghost** [comment]
> I understand, but I don’t think LibChecker needs this feature. The information displayed in the app doesn’t involve any private content; it’s all public. Therefore, I’m inclined not to add a pin lock feature.

I think it does. Like every other App, because other Apps can not acess to the App, when there is Pin enabled from the App. It does involve private content, because for example I have enabled Pin for Settings and now Apps can not see my Apps. And I understand you.

**Comment by zhaobozhen** [comment]
> > I understand, but I don’t think LibChecker needs this feature. The information displayed in the app doesn’t involve any private content; it’s all public. Therefore, I’m inclined not to add a pin lock feature.
> 
> 
> 
> I think it does. Like every other App, because other Apps can not acess to the App, when there is Pin enabled from the App. It does involve private content, because for example I have enabled Pin for Settings and now Apps can not see my Apps. And I understand you.

In fact, other applications do not access an app’s data and information through displaying its interface but rather through IPC methods, such as using a Content Provider. Therefore, the potential risks that the Pin Lock feature prevents do not come from other applications but only from “human” access. Hence, I believe it is unnecessary for the app to provide this feature.

**Comment by ghost** [comment]
> > > I understand, but I don’t think LibChecker needs this feature. The information displayed in the app doesn’t involve any private content; it’s all public. Therefore, I’m inclined not to add a pin lock feature.
> > 
> > 
> > I think it does. Like every other App, because other Apps can not acess to the App, when there is Pin enabled from the App. It does involve private content, because for example I have enabled Pin for Settings and now Apps can not see my Apps. And I understand you.
> 
> In fact, other applications do not access an app’s data and information through displaying its interface but rather through IPC methods, such as using a Content Provider. Therefore, the potential risks that the Pin Lock feature prevents do not come from other applications but only from “human” access. Hence, I believe it is unnecessary for the app to provide this feature.

Oh, I did not know that! Thank you for clarifying. I understand your point then.
