### ISSUE TITLE
[BUG] 最新版只能查看LibChecker，不能查看其他app

### ISSUE THREAD

**Issue by FlootingDream** [LibChecker/LibChecker#1406]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

最新版只能查看LibChecker，不能查看其他app，点击重载应用列表也不行

### Expected behavior / 预期行为

可以查看所有app

### Actual behavior / 实际行为

不能查看其他app，点击重载应用列表也不行

### UI / OS

Hyper OS 1

### Android Version / Android 版本

13

**Comment by zhaobozhen** [comment]
可以检查一下定制系统是否有「应用列表权限」等类似的限制操作，应用不对非标准行为做适配

**Comment by FlootingDream** [comment]
> 可以检查一下定制系统是否有「应用列表权限」等类似的限制操作，应用不对非标准行为做适配

好的，已经可以了
