### ISSUE TITLE
[FR] 支持检测APP是否使用Jetpack Compose进行UI开发

### ISSUE THREAD

**Issue by re-ovo** [LibChecker/LibChecker#145]
> Jetpack Compose 是用于构建原生 Android 界面的新工具包。它可简化并加快 Android 上的界面开发，帮助您使用更少的代码、强大的工具和直观的 Kotlin API，快速打造生动而精彩的应用。

建议加入对compose的检测，并且由于是UI级别的大型库，检测结果应该放在"该应用使用了Kotlin"那一栏上

当然现在用compose的app很少，这个FR优先级不高

**Comment by zhaobozhen** [comment]
感谢 FR。这个我是有规划支持的，只是还没想好 UI 上怎么展现。
