### ISSUE TITLE
Functionality of checking a single APP

### ISSUE THREAD

**Issue by WinDerek** [LibChecker/LibChecker#148]
It is promising to support the functionality of checking the libs of a single APP rather than all of the installed apps on the smartphone. The checking process of checking all apps is too long. Sometimes the user just wants to gain some information for some specific app.

**Comment by zhaobozhen** [comment]
Initializing application information data is a necessary condition for LibChecker to work.  In fact, this kind of long waiting for loading is only once in the lifecycle of the application, and subsequent application startup speeds will be very fast.

**Comment by WinDerek** [comment]
Am I missing some step? I must wait for the long progress bar to finish each time I re-enter LibChecker after previously closing it.

**Comment by zhaobozhen** [comment]
Seems like a bug🤔. Could you provide your device info and LibChecker version?

**Comment by WinDerek** [comment]
Oh I got it. I saved a snapshot and there is no long waiting process. Maybe it is a good idea to prompt the user (e.g., via a dialog) to save a snapshot after the very first long checking process. 🚀

**Comment by zhaobozhen** [comment]
Now that LibChecker supports comparison between APK files, I think this issue can be closed.
