### ISSUE TITLE
关于ui这方面你是如何做的这么优秀的

### ISSUE THREAD

**Issue by aacai** [LibChecker/LibChecker#149]

**Comment by zhaobozhen** [comment]
其实这个 app 的 UI 挺简单的，我是借鉴了 Material Design 和其它一些优秀的 app。其实只要关注到一些表现细节，app 整体的 UI 就会显得很协调和自然。

**Comment by aacai** [comment]
> 其实这个 app 的 UI 挺简单的，我是借鉴了 Material Design 和其它一些优秀的 app。其实只要关注到一些表现细节，app 整体的 UI 就会显得很协调和自然。

![IMG_20210921_114533.jpg](https://user-images.githubusercontent.com/62132503/134108531-bbf2fd41-acb1-4be3-8614-38154a55b8b9.jpg)
请问这个紫色的滑动控件叫什么，来自哪个项目

**Comment by zhaobozhen** [comment]
https://github.com/zhanghai/AndroidFastScroll
