### ISSUE TITLE
应用追踪功能的反馈

### ISSUE THREAD

**Issue by Harriser** [LibChecker/LibChecker#154]
机型：小米8se
软件版本：2.1.9

问题描述：
选择一个程序开启追踪功能后，当取消选择后，该程序依据保持选取状态，请问这是一个正常的设定，还是一个bug呢

![20211010182630](https://user-images.githubusercontent.com/13331604/136691995-5592a7e2-7f6b-49a2-b4a2-a2621d9aacbf.jpg)

![20211010182640](https://user-images.githubusercontent.com/13331604/136692010-7fe6f2d4-43e4-4eeb-8a5e-3ad96f523f50.jpg)

**Comment by zhaobozhen** [comment]
应该是 bug

**Comment by Harriser** [comment]
> 应该是bug

😄 好的呢，我发现另个小bug，比如我降级了一个应用“clash”，会显示有程序已被删除，重新打开软件后又会恢复正常

![20211010222335](https://user-images.githubusercontent.com/13331604/136699822-ce073507-824e-47c2-bf5c-e2dfff76cd3b.jpg)

**Comment by zhaobozhen** [comment]
5a4e8add2ab5341fd91de23b2cc130a7b7e69398 fixed
