### ISSUE TITLE
最新版显示异常，顶栏太高了

### ISSUE THREAD

**Issue by ccyykkcyk** [LibChecker/LibChecker#157]
版本号:2.1.10
![](https://cdn.jsdelivr.net/gh/ccyykkcyk/mypic@main/img/7425_origin_S11023-16422838.png)
之前的版本正常
版本号：2.1.9
![](https://cdn.jsdelivr.net/gh/ccyykkcyk/mypic@main/img/7424_origin_S11023-16415198.png)
手机型号：魅族16s

**Comment by zhaobozhen** [comment]
我回退了三方库，试一下最新版。

**Comment by ccyykkcyk** [comment]
还是高了
![](https://cdn.jsdelivr.net/gh/ccyykkcyk/mypic@main/img/7428_origin_S11023-17322376.png)
版本号：2.1.10.7283c036
应该是这个版本吧

**Comment by zhaobozhen** [comment]
2d66f3243daad4b16fb4e0cb494b0fa882f730de 已修复。
