### ISSUE TITLE
[Feature] add DEX, META DATA, PERMISSIONS, search

### ISSUE THREAD

**Issue by Pantyhose-X** [LibChecker/LibChecker#158]
add `DEX` `META DATA` `PERMISSIONS` search Statistics tab

**Comment by zhaobozhen** [comment]
Now it is a debug feature. You can input "/debugMode" at app list search box. Then in Statistics tab, you can filter dex rules. But it will take long time.

**Comment by Pantyhose-X** [comment]
> Now it is a debug feature. You can input "/debugMode" at app list search box. Then in Statistics tab, you can filter dex rules. But it will take long time.

Search results come out without displaying app

**Comment by zhaobozhen** [comment]
Supported in 1be0c0207c3185c0639975f2977148b4da4da9b4
