### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [LibChecker/LibChecker#165]
Hi @zhaobozhen 

Since this app is Apache V2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

By the way, is it possible to remove the jar [here](https://github.com/zhaobozhen/LibChecker/blob/master/app/ohos/ohos-2.1.1.21.jar) with a library or something ?

**Comment by zhaobozhen** [comment]
Hi Poussinou
Thanks for your message.

I don't want to spend too much time maintaining the app market, so I won't put LibChecker on other app markets. If anyone wants to upload my app to F-Droid, I'd be more than welcome to do so.

**Comment by momobobe** [comment]
@linsui would you like to help publish this app on F-Droid, as I see you are quite active in bringing more apps to F-Droid?

**Comment by shuvashish76** [comment]
Currently available on izzy repo : https://apt.izzysoft.de/fdroid/index/apk/com.absinthe.libchecker

According to izzy scanner it has some anti-features.

![Screenshot_2022-05-30-15-30-28](https://user-images.githubusercontent.com/48226312/170968928-a7fe9eae-47e9-4840-a786-b27ac1c49c20.jpeg)

**Comment by linsui** [comment]
Is this FOSS? https://github.com/zhaobozhen/LibChecker/blob/master/app/ohos/ohos-2.1.1.21.jar

**Comment by linsui** [comment]
It will be available in F-Droid in 2-3 day. Thanks for your help! @zhaobozhen

**Comment by shuvashish76** [comment]
Live on F-Droid : https://f-droid.org/app/com.absinthe.libchecker
