### ISSUE TITLE
快照页面出现5个应用的时候页面无法上滑

### ISSUE THREAD

**Issue by lvzhenbo** [LibChecker/LibChecker#167]
![Screenshot_2022-01-04-01-23-11-384_com.absinthe.libchecker.jpg](https://user-images.githubusercontent.com/32427677/147960473-3050c2fb-2cf7-4b05-8a4b-8e48075b5dd9.jpg)
tab栏会挡住第五个应用，并且页面无法上滑

**Comment by zhaobozhen** [comment]
Fixed in e6dba2dcef0d0a68131119ae90dd140b26ee02b1
