### ISSUE TITLE
[FR] Add a filter "sort by architecture"

### ISSUE THREAD

**Issue by FantasqueX** [LibChecker/LibChecker#169]
In order to find all apps with 32-bit architecture, I need to go to statistics, then chart, which is messy. What's more, this method cannot include system apps. I think it is reasonable to add a filter "sort by architecture".

BTW, I love this app very much. Many thanks!

**Comment by zhaobozhen** [comment]
I have added options to filter 64/32 bit apps.
![Screenshot_2022-08-21-22-41-41-696_com.absinthe.libchecker-edit.jpg](https://user-images.githubusercontent.com/25247117/185796688-74ae9aa3-7457-4b5d-973a-69f9f194a86b.jpg)
