### ISSUE TITLE
[FR] 单击目标SDK和min SDK时显示对应英文代号及Android版本

### ISSUE THREAD

**Issue by yfdyh000** [LibChecker/LibChecker#175]
参考AppChecker。其还显示本机SDK版本和各版本图标。

**Comment by zhaobozhen** [comment]
我在应用列表项中通过菜单选项配置增加了显示 Android 版本的能力。详情页由于和 AppChecker 的布局设计不同，暂不增加 Android 版本显示。
![Screenshot_2022-08-21-22-41-41-696_com.absinthe.libchecker-edit.jpg](https://user-images.githubusercontent.com/25247117/185796630-0547160f-345f-4407-82fc-c4b4eed88374.jpg)
