### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by Cicada000** [LibChecker/LibChecker#179]
Unity的LOGO在去年更新了，可以使用新的LOGO
![Screenshot_20220205-021220](https://user-images.githubusercontent.com/78632923/152581429-ac131ca8-e30e-40ec-af7c-a05a03b5245f.png)
![Screenshot_20220205-021149](https://user-images.githubusercontent.com/78632923/152581436-ac6f5221-0d23-4148-a7bd-3791f499ed02.png)

**Comment by zhaobozhen** [comment]
已更新。
