### ISSUE TITLE
希望可以加强软件信息的区分度

### ISSUE THREAD

**Issue by ron159** [LibChecker/LibChecker#22]
像是64-BIT和32-BIT均用黑色方块进行了突出显示，但是两者看上去一样，加上字体较小，需要比较仔细才能看出区别，希望可以通过颜色或者其他方式加强两者的区分。
同时也希望对Target API 进行强调，方便查看。
谢谢

**Comment by cyb233** [comment]
或许可以考虑32位底色改成偏灰一点？

**Comment by zhaobozhen** [comment]
#367
