### ISSUE TITLE
把类别和占比放在饼状图外面，并且让它可以点击（图中的32位几乎无法打开）

### ISSUE THREAD

**Issue by Doddddd** [LibChecker/LibChecker#228]
![Screenshot_20220417-231801_LibChecker.jpg](https://user-images.githubusercontent.com/88972478/163720890-6ce9739b-bbc3-47a1-8bcd-b57a5d862063.jpg)

**Comment by cyb233** [comment]
小于5%的标注单独拉出来或许合适？

**Comment by xiexiaosheng** [comment]
我也一样
![Screenshot_2022-04-26-20-23-40-155_com.absinthe.libchecker.png](https://user-images.githubusercontent.com/64482026/165299279-c755c1bd-83d9-4b11-b575-14df4fa31a43.png)
