### ISSUE TITLE
用户协议违反现有 Apache 2.0，隐私政策令人担忧

### ISSUE THREAD

**Issue by noarchwastaken** [LibChecker/LibChecker#261]
LibChecker 原有的开源协议 Apache License 2.0 允许用户拥有开源软件的基本自由：运行，修改，复制，商用。

然而 2022-05-27 添加的，看上去像是模板生成的用户协议里写着：

> 5.1. 您应该规范使用许可软件，以下方式是违反使用规范的：
> 
> 1)从事违反法律法规政策、破坏公序良俗、损害公共利益的行为。
> 
> 2)对许可软件及其中的相关信息擅自出租、出借、复制、修改、链接、转载、汇编、发表、出版、建立镜像站点，借助许可软件发展与之有关的衍生产品、作品、服务、插件、外挂、兼容、互联等。
> 
> 3)通过非由 LibChecker 及其关联公司开发、授权或认可的第三方兼容软件、系统登录或使用许可软件，或针对许可软件使用非 LibChecker 及其关联公司开发、授权或认证的插件和外挂。
> ...
> 6)复制、反汇编、修改许可软件或其任何部分或制造其衍生作品；对许可软件或者许可软件运行过程中释放在终端中的任何数据及许可软件运行过程中终端与服务器端的交互数据进行复制、修改、挂接运行或创作任何衍生作品，包括使用插件、外挂或非经授权的第三方工具/服务接入许可软件和相关系统等形式。

这些条款很明显违反了上述的四条自由。

5.1.1 还同时违反了开源软件“不歧视”的原则，比如中国法律禁止，但在国际上允许的行为。

关于同时新增的隐私政策，我能理解您这么做可能是为了继续在酷安上架或是备案所需，并且 LibChecker 本身除了 AppCenter 分析和获取规则和描述之外并没有联网，但对于我来讲跟其他国产软件如出一辙的用词之广实在难以接受。

我注意到 FOSS 版并没有显示弹窗，但如果这些政策是明确针对国内/酷安版，而不是其它地方的，请在两个文档里面写明。这样，这个政策仅对酷安版的二进制有效，其他人依然可以对源码享受上述四条自由。如果您以后要在酷安版内加入专有组件，这个协议就会适用于酷安版及里面的专有组件。

抱歉在 issues 里面提程序本身无关的话题，这个 issue 也不是法律建议，虽然大概率这两条协议永远不会用到，但以防万一的法律文件请谨防一万。

**Comment by zhaobozhen** [comment]
感谢您的建议，确实我在用户协议这方面没有什么经验，没有考虑到这些。我会在后面再修订一下文案。

**Comment by zhaobozhen** [comment]
已经删除用户协议相关内容。
