### ISSUE TITLE
能不能增加一个区分颜色，目前：32 BIT和64 BIT都是黑色背景

### ISSUE THREAD

**Issue by hulang** [LibChecker/LibChecker#263]
应用：能不能增加一个区分颜色，目前：32 BIT和64 BIT都是黑色背景
如：32 BIT给个蓝色背景，64 BIT可以依旧黑色背景
![微信图片_20220531130934](https://user-images.githubusercontent.com/4961831/171097230-37e9de14-fcb8-46a8-8028-fc2abf6e41fa.jpg)

**Comment by zhaobozhen** [comment]
关于这个建议其实我一直在考虑怎么做。因为考虑到应用列表页是进入 app 的第一个页面，所以我不想加入很多不同的颜色让它变得太过花哨。因此还没想到一个合适的区分两种标签的方案。其实对于区分 32 位和 64 位应用，图表中的过滤标签是否就够用了呢？

**Comment by hulang** [comment]
@zhaobozhen 我基本都是直接查看的是第一个页面：应用，看看是否32/64，不弄颜色。。。一个个看，眼睛疼。。。

**Comment by zhaobozhen** [comment]
与 #22 重复问题
