### ISSUE TITLE
[功能请求]长按或点击“应用”底栏，弹出Toast显示应用数量

### ISSUE THREAD

**Issue by Doddddd** [LibChecker/LibChecker#268]

**Comment by Positivelight775** [comment]
Did you check the change log

**Comment by Positivelight775** [comment]
If you can make a note on the original note before you send it to me write something on there in regards to the caller being harassed or hacked indicated that Kevin Robert Davis was the culprit

**Comment by Positivelight775** [comment]
If you can make a note on the original note before you send it to me write something on there in regards to the caller being harassed or hacked indicated that Kevin Robert Davis was the culprit

**Comment by Positivelight775** [comment]
Planted the sead

**Comment by Positivelight775** [comment]
How can I send you the seed without it causing you harm or tracking you

**Comment by Positivelight775** [comment]
{{{[https://github.com/mozilla-mobile/focus-android/pull/7174]}}}

Like this correct...

**Comment by zhaobozhen** [comment]
这个交互显得很奇怪，我会想想如何设计这个需求。现在可以在快照页面看到应用程序数量。

**Comment by Doddddd** [comment]
> 这个交互显得很奇怪，我会想想如何设计这个需求。现在可以在快照页面看到应用程序数量。

安装或卸载软件，快照页面的数量不会变，需要重新保存快照
![Screenshot_20220609-135944_LibChecker.jpg](https://user-images.githubusercontent.com/88972478/172775528-5ce8616d-6123-4a89-afad-4ed8845bce61.jpg)
这个怎么样

**Comment by zhaobozhen** [comment]
> > 这个交互显得很奇怪，我会想想如何设计这个需求。现在可以在快照页面看到应用程序数量。
> 
> 安装或卸载软件，快照页面的数量不会变，需要重新保存快照
> ![Screenshot_20220609-135944_LibChecker.jpg](https://user-images.githubusercontent.com/88972478/172775528-5ce8616d-6123-4a89-afad-4ed8845bce61.jpg)
> 这个怎么样

这个看起来挺好，我借鉴一下😜
