### ISSUE TITLE
显示已达 android:maxSdkVersion 的权限 (Show permissions that have reached android:maxSdkVersion)

### ISSUE THREAD

**Issue by AyakaAgo** [LibChecker/LibChecker#285]
![Screenshot_2022-06-24-13-19-32-369-edit_com agyer windmill](https://user-images.githubusercontent.com/20831549/175467568-819603b2-512a-4a26-a60c-f46dfcc3f5b1.jpg)

使用 `ManifestReader` 获取并在“权限”标签页显示不包含在 `PackageInfo#requestedPermissions` 的已达 [`android:maxSdkVersion`](https://developer.android.google.cn/guide/topics/manifest/uses-permission-element?hl=en#maxSdk)  的权限。

即使系统可能不再使用它们，但这才是*完整的*权限列表。

-----------------------

Use `ManifestReader` to obtain and show the permissions that have reached [`android:maxSdkVersion`](https://developer.android.google.cn/guide/topics/manifest/uses-permission-element?hl=en#maxSdk) and are not included in `PackageInfo#requestedPermissions` on the "Permissions" tab.

Even though the system may no longer use them, this is the *complete* list of permissions.

**Comment by zhaobozhen** [comment]
很好的建议，我将在后续版本实现。

**Comment by su1216** [comment]
对于已安装的应用，在特定的环境中应用不同的权限，这不应该算是不完整展示。

**Comment by zhaobozhen** [comment]
> 对于已安装的应用，在特定的环境中应用不同的权限，这不应该算是不完整展示。

算是未安装的权限吧，可以考虑看看怎么展示。

**Comment by zhaobozhen** [comment]
e1c823cf50d6f7403d04711296b83c3332b10e25
