### ISSUE TITLE
显示min api level

### ISSUE THREAD

**Issue by cyb233** [LibChecker/LibChecker#29]
如题，除target api level外，再添加min api level

**Comment by zhaobozhen** [comment]
Added in this commit: https://github.com/zhaobozhen/LibChecker/commit/96c43868e0cef34d84a215f731a4ff113f589231

**Comment by cyb233** [comment]
> Added in this commit: [96c4386](https://github.com/zhaobozhen/LibChecker/commit/96c43868e0cef34d84a215f731a4ff113f589231)

既然加好了这个信息不如把排序也加上？
