### ISSUE TITLE
在“进一步操作”中显示“应用中的其他设置”入口 (Show "Additional settings in the app" in "Further Opeartions" dialog)

### ISSUE THREAD

**Issue by AyakaAgo** [LibChecker/LibChecker#294]
###### *与主功能不太相关，可选添加。Not very relevant to the main function, optional to add.*

![应用信息中的“应用中的其他设置”选项 ("Additional settings in the app" in App info system Settings')](https://user-images.githubusercontent.com/20831549/176375296-aad76c97-c19f-4591-88b7-16161d44b232.jpg)

**针对某些已移除/隐藏了某些设置项目的第三方系统。**~~(MIUI)~~

如果应用含有应用内设置 *(SettingsActivity)*，开发者可以通过在相关 `<activity>` 中添加含有 [`ACTION_APPLICATION_PREFERENCES`](https://developer.android.google.cn/reference/android/content/Intent?hl=en#ACTION_APPLICATION_PREFERENCES) action 的 `<intent-filter>`。

第三方应用可以通过 `Intent#setAction()`, `Intent#setPackage()`, `Intent#resolveActivity()` 来查询某个应用是否含有 *SettingsActivity*。*系统设置也是以此方法获取的[^aosp_cn]，但它不受`android:exported`值影响。*

---------------------------

**For some third-party systems with some settings options removed/hidden.**

If an app has in-app settings *(SettingsActivity)*, developer can add `<intent-filter>` with [`ACTION_APPLICATION_PREFERENCES`](https://developer.android.google.cn/reference/android/content/Intent?hl=en#ACTION_APPLICATION_PREFERENCES) action in relative `<activity>`(s).

Third-party apps can query whether an app contains *SettingsActivity* through `Intent#setAction()`, `Intent#setPackage()`, `Intent#resolveActivity()`. *System Settings app is also obtained in this way[^aosp_en], but it isn‘t restricted by `android:exported`.*

```xml
<activity
    ......
    >
    <intent-filter>
        <action
            android:name="android.intent.action.APPLICATION_PREFERENCES" />
    </intent-filter>
</activity>
```

###### *LibChecker 也可以添加此 `action`，在启动时将用户带到“设置”页。LibChecker can also add this `action` to take user to “Settings” page.*

[^aosp_cn]: AOSP 中的“设置”源代码：[com.android.settings.applications.appinfo.AppSettingPreferenceController#getAvailabilityStatus](http://aospxref.com/android-12.0.0_r3/xref/packages/apps/Settings/src/com/android/settings/applications/appinfo/AppSettingPreferenceController.java#43)

[^aosp_en]: System Settings source code in AOSP: [com.android.settings.applications.appinfo.AppSettingPreferenceController#getAvailabilityStatus](http://aospxref.com/android-12.0.0_r3/xref/packages/apps/Settings/src/com/android/settings/applications/appinfo/AppSettingPreferenceController.java#43)

**Comment by zhaobozhen** [comment]
已支持，感谢如此详尽的说明。
