### ISSUE TITLE
建议允许筛选已标记/未标记的库

### ISSUE THREAD

**Issue by yfdyh000** [LibChecker/LibChecker#318]
“统计”界面的原生库、组件等，允许只显示已标记/未标记的库、组件、权限等。

**Comment by zhaobozhen** [comment]
这个也许会在近期的新版本中提供。目前可以在搜索列表输入 /debugmode 开启隐藏菜单，输入 /usermode 可以恢复正常模式

**Comment by zhaobozhen** [comment]
Done
