### ISSUE TITLE
建议将APK安装日期等记录为"用户元数据"

### ISSUE THREAD

**Issue by yfdyh000** [LibChecker/LibChecker#320]
增强“快照”价值。

建议：安装日期、更新日期、安装源（包名和label）、是否“系统应用”。
https://github.com/ghmxr/apkextractor APK Kit 可查看这些数据。
UID、路径、主启动类等，感觉可能不必要。
记录时间的隐私方面，不知道是否需考虑。

**Comment by zhaobozhen** [comment]
我对于 LibChecker 的设计原则是专精，因此在功能的添加上尽可能围绕 “Lib” 本身。越来越多的信息数据会让用户觉得应用越来越复杂，而且这些信息的查看市面上也有更专业的软件来平替，所以暂时不考虑添加。
