### ISSUE TITLE
进一步操作 (further_operation) 按钮应始终显示

### ISSUE THREAD

**Issue by yfdyh000** [LibChecker/LibChecker#321]
不知为何，按钮仅在详情页里向上滑动后显示。启动应用、查看应用详情等功能，很实用。

**Comment by zhaobozhen** [comment]
事实上就是这么设计的，因为标题栏完全展开时可以通过点击应用图标呼出进一步操作，而标题栏折叠时为了可以打开进一步操作，才添加了工具栏的火箭图标。
