### ISSUE TITLE
建议提供更多统计图表

### ISSUE THREAD

**Issue by yfdyh000** [LibChecker/LibChecker#323]
如是否使用了 App Bundles，extractNativeLibs的值，等等。

以及是否考虑 #320 中建议的“安装源”，虽然与应用本身的关系不明显，但可能帮助辨识应用来源（系统应用商店、Google Play商店、APK文件安装）。

**Comment by zhaobozhen** [comment]
当然，图表界面未来会加入更多的统计项。但在这之前，我需要设计一套展示效果更好的切换类型组件代替现在的 ChipGroup
