### ISSUE TITLE
[bug] 底栏异常显示

### ISSUE THREAD

**Issue by Doddddd** [LibChecker/LibChecker#331]
应用页面搜索结果超过一页的时候，输入法上面会显示底栏，不超过一页不显示，而统计页面任何情况下都会显示底栏，我觉得统一不显示比较好。
![Screenshot_20220722-212113_LibChecker](https://user-images.githubusercontent.com/88972478/180448404-79610461-70fe-4e0a-804a-22aefd8a93cb.jpg)
![Screenshot_20220722-212124_LibChecker](https://user-images.githubusercontent.com/88972478/180448434-cec9f00e-fde0-4a80-a6b5-06fb250df04c.jpg)

**Comment by zhaobozhen** [comment]
应用列表页不显示底栏是 bug，我是设计成始终显示底栏的，这样方便任何时候切换 tab。
