### ISSUE TITLE
列出intent-filter中的URL scheme

### ISSUE THREAD

**Issue by cyb233** [LibChecker/LibChecker#334]
如果难以实现就算了

**Comment by zhaobozhen** [comment]
可以说说使用场景吗？我觉得这和应用的主要功能有点偏离。

**Comment by cyb233** [comment]
有时无文档时想知道scheme有哪些以便调用，但是要找到并解压apk再反编译AndroidManifest.xml实在太麻烦，所以希望有更快捷的方法，虽然感觉我的需求确实与项目描述有些偏离
