### ISSUE TITLE
部分原生库的图标会变成app主颜色（紫色）

### ISSUE THREAD

**Issue by qhy040404** [LibChecker/LibChecker#345]
![IMG_20220730_223712](https://user-images.githubusercontent.com/45379733/181919250-ca337abe-fa39-44f7-8f33-335a9371fcaa.jpg)

**Comment by zhaobozhen** [comment]
这不是 bug，对于单色的图标会以主题色显示。目前除了手机品牌和多色 logo 都会以主题色来显示。

**Comment by qhy040404** [comment]
OK 👍🏻
