### ISSUE TITLE
[功能请求] 安装包备份

### ISSUE THREAD

**Issue by Pantyhose-X** [LibChecker/LibChecker#358]
通过 [FTP 服务器](https://github.com/ppareit/swiftp) 把安装包传输到PC。不消耗存储空间

### 为什么要怎么做
最新版的应用不一定是最好的，网上找不到旧版的安装包。

如果手机坏了，或换新手机。PC上还有安装包，不用浪费大量时间在找旧版安装包上。

现在的市场上的安装包备份，都没有传输到其他地方的功能，都是备份到内部存储。没有足够的存储空间就备份不了。我安装了600多个应用30多G，没有足够的存储空间来备份。 

所以如果[FTP 服务器](https://github.com/ppareit/swiftp) 一个一个的把安装包传输到PC。我就可以备份了。

**Comment by yfdyh000** [comment]
我有类似需求，但我想这超出作者设想的该应用功能范围。提供FTP的性能和稳定性，可能也不好。

对此需求，建议参考 https://gist.github.com/AnatomicJC/e773dd55ae60ab0b2d6dd2351eb977c1?permalink_comment_id=4138890#gistcomment-4138890 ，用ADB命令备份到PC。然后可以将APK传到网盘。
需注意，app bundle的APK，这可能无法完整备份。

**Comment by zhaobozhen** [comment]
没有看出这个需求和 LibChecker 有什么关联。换句话说，这个需求为什么是 LibChecker 来做，而不是更专门的 app 来做呢？

**Comment by su1216** [comment]
LibChecker似乎不应和备份扯上关系
