### ISSUE TITLE
[FR] Enhanced snapshot

### ISSUE THREAD

**Issue by qhy040404** [LibChecker/LibChecker#389]
Kotlin version, AGP version, Compose version

Feature differences

**Comment by zhaobozhen** [comment]
In fact, recording these features is very time consuming and would result in a significant increase in the retention time of the snapshot, so I have not recorded this information for now.

**Comment by qhy040404** [comment]
I've actually been evaluating this new feature. Some of the components mentioned are not updated very often, so it may not be important to detect the update of the component. It also increases the time to generate snapshots.
