### ISSUE TITLE
通知栏进度条不跟随主题色

### ISSUE THREAD

**Issue by Doddddd** [LibChecker/LibChecker#400]
三星 S21
One UI 4.1
Android 12

![Screenshot_20220908-010835_LibChecker](https://user-images.githubusercontent.com/88972478/188938959-29b78008-e965-46d1-aa88-63726fefa569.png)
![Screenshot_20220908-011234_LibChecker](https://user-images.githubusercontent.com/88972478/188939065-0a541ca0-4567-48bb-bc19-bc833cce379c.png)

**Comment by qhy040404** [comment]
应该是触发概率比较小的bug
![IMG_20220908_162900.jpg](https://user-images.githubusercontent.com/45379733/189074401-2b4dcaef-e902-4ac3-b027-6e776ab660f6.jpg)
![Screenshot_2022-09-08-16-27-05-324_com.absinthe.libchecker.jpg](https://user-images.githubusercontent.com/45379733/189074439-c2b44f08-e59a-42b9-9667-3bbd3ab95391.jpg)

**Comment by qhy040404** [comment]
建议提供安卓版本及定制 UI 类型（如MIUI，ColorOS .....）
 > 本地测试 Android 12 (31) 以上复现失败
> Android 12 以下无 MD3 ，复现均为紫色，程序主色也为紫色，非bug

**Comment by Doddddd** [comment]
> 建议提供安卓版本及定制 UI 类型（如MIUI，ColorOS .....）
>  > 本地测试 Android 12 (31) 以上复现失败
> > Android 12 以下无 MD3 ，复现均为紫色，程序主色也为紫色，非bug

三星 S21
One UI 4.1
Android 12

**Comment by Doddddd** [comment]
https://user-images.githubusercontent.com/88972478/189338960-dad8f249-2a02-4ed5-9668-286e325ffac7.mp4

问题依然存在

**Comment by qhy040404** [comment]
reopen一下 @Doddddd

**Comment by qhy040404** [comment]
[LibChecker-2.3.1.dev.9c5d3203-1383-foss-debug.zip](https://github.com/zhaobozhen/LibChecker/files/9535062/LibChecker-2.3.1.dev.9c5d3203-1383-foss-debug.zip)

试一下这个debug版本 @Doddddd

**Comment by Doddddd** [comment]
> [LibChecker-2.3.1.dev.9c5d3203-1383-foss-debug.zip](https://github.com/zhaobozhen/LibChecker/files/9535062/LibChecker-2.3.1.dev.9c5d3203-1383-foss-debug.zip)
> 
> 试一下这个debug版本 @Doddddd

debug版正常（没有权限重新打开）

**Comment by qhy040404** [comment]
[LibChecker-2.3.1.dev.09a9c657-1384-foss-release.zip](https://github.com/zhaobozhen/LibChecker/files/9535162/LibChecker-2.3.1.dev.09a9c657-1384-foss-release.zip)

再试一下这个ci配置输出的版本，我改包名了，不会冲突 @Doddddd

**Comment by Doddddd** [comment]
> [LibChecker-2.3.1.dev.09a9c657-1384-foss-release.zip](https://github.com/zhaobozhen/LibChecker/files/9535162/LibChecker-2.3.1.dev.09a9c657-1384-foss-release.zip)
> 
> 再试一下这个ci配置输出的版本，我改包名了，不会冲突 @Doddddd 

正常

**Comment by qhy040404** [comment]
> > [LibChecker-2.3.1.dev.09a9c657-1384-foss-release.zip](https://github.com/zhaobozhen/LibChecker/files/9535162/LibChecker-2.3.1.dev.09a9c657-1384-foss-release.zip)
> > 再试一下这个ci配置输出的版本，我改包名了，不会冲突 @Doddddd
> 
> 正常

麻烦了，谢谢

**Comment by Doddddd** [comment]
> > > [LibChecker-2.3.1.dev.09a9c657-1384-foss-release.zip](https://github.com/zhaobozhen/LibChecker/files/9535162/LibChecker-2.3.1.dev.09a9c657-1384-foss-release.zip)
> > > 再试一下这个ci配置输出的版本，我改包名了，不会冲突 @Doddddd
> > 
> > 正常
> 
> 麻烦了，谢谢
谢谢
