### ISSUE TITLE
某个APP无法在未安装时分析

### ISSUE THREAD

**Issue by jimstar06** [LibChecker/LibChecker#41]
故障APP：[https://app.mi.com/details?id=com.hicorenational.antifraud](商店地址)

测试环境：MIUI 12.5 21.5.12 小米9 Android 11

故障描述：通过第三方文件管理器选择位于SD卡中的apk文件-打开方式-查看App详情，只能看到基本信息，所有列表均为空。

![jpg](https://user-images.githubusercontent.com/12005178/120827755-59598900-c58e-11eb-9c9b-55e628032f56.jpg)

该APP安装后可以被LibChecker正常分析。

**Comment by zhaobozhen** [comment]
我这边没有复现到，请在后面的版本更新中关注是否还有此问题。

**Comment by su1216** [comment]
具体是哪个第三方文件管理器

**Comment by jimstar06** [comment]
测试过能复现的文件管理器（均来自Google Play）：Google文件极客、CX File Explorer、 FX File Explorer
LibChecker: 2.0.13、2.0.14均有问题
待分析反诈骗APP: 1.1.6及1.1.7均有问题，但能正确识别32/64位、Target API、minSDKVersion
APK文件均放在内置SD卡中，由于放相同目录的QQ的APK可以正常分析，所以我猜测不是系统或者权限问题导致的。

**Comment by zhaobozhen** [comment]
已修复
