### ISSUE TITLE
[BUG] LibChecker与鸿蒙相关的问题收集

### ISSUE THREAD

**Issue by su1216** [LibChecker/LibChecker#467]
### LibChecker version / LibChecker 版本

最新版本

### Bug description / Bug 描述

收集LibChecker任何与鸿蒙相关的bug反馈，页面展示、LibChecker自身业务逻辑问题不在此issue收集范围之内。如果应用崩溃，请提供相关日志

### Expected behavior / 预期行为

正常工作

### Actual behavior / 实际行为

工作异常

### Harmony版本

Harmony OS 版本
OpenHarmony 版本

### Android Version / Android 版本

任何版本

**Comment by qhy040404** [comment]
Remove assignee and label. And pin this issue.

**Comment by qhy040404** [comment]
abilityinfo里面含有exported参数吗:eyes:

**Comment by qhy040404** [comment]
https://www.coolapk.com/feed/42928037?shareKey=OGE5MzM4MTFjOWZkNjNkYTk0YTk~&shareUid=2382853&shareFrom=com.coolapk.market_13.0.1

**Comment by su1216** [comment]
> https://www.coolapk.com/feed/42928037?shareKey=OGE5MzM4MTFjOWZkNjNkYTk0YTk~&shareUid=2382853&shareFrom=com.coolapk.market_13.0.1

和鸿蒙无关，只和android相关 @zhaobozhen

**Comment by qhy040404** [comment]
> > https://www.coolapk.com/feed/42928037?shareKey=OGE5MzM4MTFjOWZkNjNkYTk0YTk~&shareUid=2382853&shareFrom=com.coolapk.market_13.0.1
> 
> 和鸿蒙无关，只和android相关 @zhaobozhen 
> 

这个问题我记得我在酷安回答过一个类似的，就是因为分屏那个api是api32引进的，hm3是31

**Comment by qhy040404** [comment]
> > https://www.coolapk.com/feed/42928037?shareKey=OGE5MzM4MTFjOWZkNjNkYTk0YTk~&shareUid=2382853&shareFrom=com.coolapk.market_13.0.1
> 
> 和鸿蒙无关，只和android相关
> 

这不就是我回答那个吗![Screenshot_2023-03-27-11-31-58-032_com.coolapk.market.jpg](https://user-images.githubusercontent.com/45379733/227834242-a372392d-474b-4b47-9dec-5b476847880e.jpg)

**Comment by su1216** [comment]
由于鸿蒙之后将不再支持Android应用，并且目前的鸿蒙4很多api也不再适用于Android应用，所以关闭此issue
