### ISSUE TITLE
[FR] 建议在ABI图标里显示x86架构64位和32位应用

### ISSUE THREAD

**Issue by EvatsugDnalloR** [LibChecker/LibChecker#468]
### Enhancement propose / 改进目的

这个建议主要是给WSA设备的，毕竟WSA上大部分应用用的都是x86架构，arm只是少数

### Solution / 解决方案

在同一张表里同时显示arm和x86架构的64和32位的应用（再加上无原生库的）

### Additional info / 额外信息

虽然不是很必要，但有总比没有好

**Comment by qhy040404** [comment]
有点没听懂，你是说统计里面的图表还是哪里

**Comment by EvatsugDnalloR** [comment]
> 有点没听懂，你是说统计里面的图表还是哪里

没错就是统计图表里，目前只显示arm32和arm64加上无原生库，希望加上x86和x86_64

**Comment by qhy040404** [comment]
Fixed by #444, #445

这个已经提交进master了，等2.3.3发布吧

**Comment by EvatsugDnalloR** [comment]
> Fixed by #444, #445
> 
> 这个已经提交进master了，等2.3.3发布吧

好的谢谢
