### ISSUE TITLE
[BUG] Version name

### ISSUE THREAD

**Issue by qhy040404** [LibChecker/LibChecker#477]
### LibChecker version / LibChecker 版本

2.3.3

### Bug description / Bug 描述

2.3.3版本号带dev

### Expected behavior / 预期行为

None

### Actual behavior / 实际行为

None

### UI / OS

None

### Android Version / Android 版本

None

**Comment by zhaobozhen** [comment]
因为我在 build 时删除了 tag 导致的，重新跑一下应该就好了。
