### ISSUE TITLE
关于点击查看权限标签那一栏，希望能增加翻译

### ISSUE THREAD

**Issue by OSNewbie** [LibChecker/LibChecker#485]
感觉很多感觉有点费劲，嗯，翻译暂时不着急，

**Comment by qhy040404** [comment]
如果要翻译也只能翻译安卓原生存在的权限和部分push的权限，app自己定义的权限也无法翻译

---

> Update:

可并入rules-bundle

**Comment by zhaobozhen** [comment]
现在已经支持单击时显示权限描述信息
