### ISSUE TITLE
[BUG] Assist Us Link is broken

### ISSUE THREAD

**Issue by 825i** [LibChecker/LibChecker#493]
### LibChecker version / LibChecker 版本

2.3.4

### Bug description / Bug 描述

When trying to click this link
![Screenshot_20221201_060839_LibChecker](https://user-images.githubusercontent.com/58630825/204963923-79fc02e3-92a7-449d-872e-6baace87772e.jpg)

You ger 404 error below because the Repo link changed
![Screenshot_20221201_060901_Chrome](https://user-images.githubusercontent.com/58630825/204963943-37917dad-96e6-441f-9599-55b6616af496.jpg)

### Expected behavior / 预期行为

It should go to this Repo

### Actual behavior / 实际行为

You get a 404 page on Github because the Repo link changed

### UI / OS

Android

### Android Version / Android 版本

13

**Comment by qhy040404** [comment]
Already fixed by a457968

**Comment by zhaobozhen** [comment]
Reopened the issues module of the old repo. Please try again.

**Comment by qhy040404** [comment]
> Reopened the issues module of the old repo. Please try again.

Release a new version is a better way to fix this.
