### ISSUE TITLE
[FR] Support for Dart-lang

### ISSUE THREAD

**Issue by 825i** [LibChecker/LibChecker#494]
### Enhancement propose / 改进目的

There is no support for Dart. Many of my apps are made in Dart. This app is 99% written in Dart. But it shows Kotlin icon.

![Screenshot_20221201_061238_LibChecker](https://user-images.githubusercontent.com/58630825/204964231-38c9fb64-674d-4583-a28c-952f2d8ea06b.jpg)

### Solution / 解决方案

Add Dart feature and also Go-lang.

**Comment by qhy040404** [comment]
https://github.com/vfsfitvnm/ViMusic
It's written in Kotlin

**Comment by zhaobozhen** [comment]
If you can, please list a few apps written using Dart, I don't have a clue how to check Dart right now.

**Comment by 825i** [comment]
Sorry my mistake, I meant this app: https://play.google.com/store/apps/details?id=com.saltycrackers.tables

Though it does show Flutter libs just not the Dart or Flutter icon. But the Kotlin icon.

![Screenshot_20221202_023712_LibChecker](https://user-images.githubusercontent.com/58630825/205192994-8a5bf96c-7119-430e-8752-6291dc1e7c2c.jpg)

There is also this app which is 100% Flutter and doesn't really show anything:
![Screenshot_20221202_024146_LibChecker](https://user-images.githubusercontent.com/58630825/205193031-9ef3cb59-d6b0-4bb2-9490-f41b6cc45d43.jpg)

**Comment by 825i** [comment]
Other full Dart (Flutter) examples:

https://play.google.com/store/apps/details?id=co.banano.natriumwallet

https://play.google.com/store/apps/details?id=com.chechu.cherry

https://play.google.com/store/apps/details?id=me.wozappz.deer

**Comment by qhy040404** [comment]
> Sorry my mistake, I meant this app: https://play.google.com/store/apps/details?id=com.saltycrackers.tables
> 
> Though it does show Flutter libs just not the Dart or Flutter icon. But the Kotlin icon.
> 
> ![Screenshot_20221202_023712_LibChecker](https://user-images.githubusercontent.com/58630825/205192994-8a5bf96c-7119-430e-8752-6291dc1e7c2c.jpg)
> 
> There is also this app which is 100% Flutter and doesn't really show anything: ![Screenshot_20221202_024146_LibChecker](https://user-images.githubusercontent.com/58630825/205193031-9ef3cb59-d6b0-4bb2-9490-f41b6cc45d43.jpg)

Flutter icons are showed in Native libraries. Do you mean you want to see the icon near the Kotlin icon?

**Comment by 825i** [comment]
Yes that would be great. I think it would make more sense as it's totally possible to write apps without using any Kotlin libraries at all.

Here's another 100% Dart example:

![Screenshot_20221207_034516_LibChecker](https://user-images.githubusercontent.com/58630825/206067296-5356758e-b852-4613-9a66-cb25f73d8356.jpg)

**Comment by qhy040404** [comment]
> Yes that would be great. I think it would make more sense as it's totally possible to write apps without using any Kotlin libraries at all.
> 
> Here's another 100% Dart example:
> 
> ![Screenshot_20221207_034516_LibChecker](https://user-images.githubusercontent.com/58630825/206067296-5356758e-b852-4613-9a66-cb25f73d8356.jpg)
> 

Check the source of any apps you mentioned. It's not possible to write an app with only Dart. They need Kotlin or Java to implement Flutter. 

---

This is the Kotlin code in the app "Musify" you mentioned.
https://github.com/gokadzev/Musify/blob/master/android/app/src/main/kotlin/com/gokadzev/musify/MainActivity.kt

**Comment by qhy040404** [comment]
For example, check this Flutter project.
https://github.com/canhuah/WanAndroid-Flutter/blob/master/android/app/src/main/java/com/canhuah/wanandroid/MainActivity.java 
It needs Java or Kotlin to implement `FlutterActivity` class.
