### ISSUE TITLE
[BUG] 360加固标签缺失

### ISSUE THREAD

**Issue by ArthurCyy** [LibChecker/LibChecker#509]
### LibChecker version / LibChecker 版本

2.3.4.7c927c8a (1448)

### Bug description / Bug 描述

360加固标签缺失

### Expected behavior / 预期行为

360加固标签存在

### Actual behavior / 实际行为

360加固标签缺失
![Screenshot_2022-12-11-14-17-01-823_com absinthe libchecker-edit](https://user-images.githubusercontent.com/37627147/206889387-4655568c-1c13-467c-ae0a-cf06864a62e5.jpg)

### UI / OS

MIUI

### Android Version / Android 版本

12

**Comment by yfdyh000** [comment]
https://github.com/LibChecker/LibChecker-Rules/discussions/349

**Comment by ArthurCyy** [comment]
> [LibChecker/LibChecker-Rules#349](https://github.com/LibChecker/LibChecker-Rules/discussions/349)

检测方法似乎不对或已过时？因为像酷安这样的明确已知采用了360加固的软件仍未显示标签

**Comment by zhaobozhen** [comment]
看一下 dex 栏

**Comment by ArthurCyy** [comment]
> 看一下 dex 栏

![Screenshot_2022-12-11-14-35-42-149_com absinthe libchecker-edit](https://user-images.githubusercontent.com/37627147/206889927-67e0bed3-bd4d-43a9-93da-8896bef9f31a.jpg)
Dex也表明酷安采用了360加固，但未显示标签，建议可以根据Dex来判断是否采用360加固

**Comment by qhy040404** [comment]
酷安的dex里面没有`QHClassLoader`，感觉检测`com.qihoo.util.Configuration`这个类会更好
![Screenshot_2022-12-11-14-49-59-492_bin mt plus-edit](https://user-images.githubusercontent.com/45379733/206890381-38a2b156-16b2-435b-814d-d5c984faf7e7.jpg)
![Screenshot_2022-12-11-14-49-33-259_bin mt plus-edit](https://user-images.githubusercontent.com/45379733/206890383-5f9d7ec6-3f23-47f7-97db-949ce5575e8b.jpg)
![Screenshot_2022-12-11-14-50-47-831_bin mt plus-edit](https://user-images.githubusercontent.com/45379733/206890384-b836c409-dce0-482f-9d1a-217764851ae3.jpg)

**Comment by ArthurCyy** [comment]
> 看一下 dex 栏

![Screenshot_2022-12-11-14-48-06-732_bin mt plus-edit](https://user-images.githubusercontent.com/37627147/206890324-8273a0fe-f1b0-4033-a92c-e9676366fb33.jpg)
看了几个使用360加固的软件都是这样，可能360加固那边有改动，建议检测`com.qihoo.util.Configuration`或者`com.stub.StubApp`吧
