### ISSUE TITLE
[FR] Help F-Droid auto update

### ISSUE THREAD

**Issue by linsui** [LibChecker/LibChecker#516]
### Enhancement propose / 改进目的

We got the version name and version code from the apk name in https://github.com/LibChecker/LibChecker/releases in the past. But recently GitHub put the assets info into another page and load it dynamically so we can't get it anymore. Currently LibChecker is updated manully.

### Solution / 解决方案

Could you please add the version name and version code in the release notes so that we can get it from the release page? Or you can add a version.txt in the release files so that we can get it from https://github.com/LibChecker/LibChecker/releases/latest/download/version.txt . Thanks!

**Comment by zhaobozhen** [comment]
Any samples I can refer to?

**Comment by linsui** [comment]
https://github.com/home-assistant/android/releases/tag/2022.11.0 This is an example for version code. You can use a version.txt file with

```
versionCode=1465
versionName=2.3.5.fbbe4e0d
```

or simply

```
2.3.5.fbbe4e0d-1465
```

and publish it along with the apks.

**Comment by zhaobozhen** [comment]
Added

**Comment by linsui** [comment]
Thanks!

**Comment by licaon-kter** [comment]
Can this be reopened?

versionCode seems to be stuck at the same version in the APK: https://gitlab.com/fdroid/fdroiddata/-/jobs/4045737901#L429
