### ISSUE TITLE
[FR] Allow libchecker to check apps that are not installed

### ISSUE THREAD

**Issue by jcperil** [LibChecker/LibChecker#531]
### Enhancement propose / 改进目的

Currently, we can check only those apps which are installed on the device. This request is to allow checking libraries of apps that are not installed as well.

**Comment by zhaobozhen** [comment]
Hi, LibChecker supports checking the details of apk files directly, you just need to enable “apk analysis” in the settings page, and then share the target apk to LibChecker via file manager.
