### ISSUE TITLE
[FR] 优化平行视界

### ISSUE THREAD

**Issue by Doddddd** [LibChecker/LibChecker#532]
### Enhancement propose / 改进目的

![Screenshot_20230104-011221_LibChecker](https://user-images.githubusercontent.com/88972478/210406936-ab2daf56-d8f6-449c-9ce3-df0dae0ea804.png)
![Screenshot_20230104-011537_LibChecker](https://user-images.githubusercontent.com/88972478/210407361-9662177c-4d03-42bd-bc58-8d90038ee0a6.png)
竖屏状态下的平板模式效果很差，希望能只在横屏使用平板模式，或者可以手动关闭

### Solution / 解决方案

自动或手动关闭

**Comment by qhy040404** [comment]
> 其实平板没专门适配...😳

瞎了，没看到`split_config`

**Comment by Doddddd** [comment]
> 其实平板没专门适配...😳

这个应该叫平行视界吧，有优化的打算吗？
