### ISSUE TITLE
[BUG] 看到的Amethyst的Jetpack Compose版本乱码

### ISSUE THREAD

**Issue by realth000** [LibChecker/LibChecker#565]
### LibChecker version / LibChecker 版本

2.3.6.e69c5d44

### Bug description / Bug 描述

查看从Google Play下载的Amethyst时看到的Jetpack Compose版本不正确（是乱码）。

### Expected behavior / 预期行为

看到的结果和从其他使用了Compose的app看到的一样，是正确的版本号，比如`1.2.0`，`1.4.0-alpha2`。

### Actual behavior / 实际行为

![微信图片_20230202234827](https://user-images.githubusercontent.com/59462104/216373832-5f88a2e4-2252-486f-8cc4-4e826afab7bb.jpg)
![微信图片_20230202234836](https://user-images.githubusercontent.com/59462104/216373855-fdab9ea4-9529-4ba1-89b2-c19ecdec70c7.jpg)

### Steps to reproduce / 复现步骤

1. 从Google Play安装Amethyst。
2. 查看Amethyst的Compose版本。

### UI / OS

MIUI 14

### Android Version / Android 版本

13

### Additional info / 额外信息

其他app的Compose版本都正确

**Comment by qhy040404** [comment]
这不是bug，这个app的metadata里面就是这么写的
可解压apk后查看META-INF中的
```
"androidx.compose.runtime_runtime.version",
"androidx.compose.ui_ui.version",
"androidx.compose.ui_ui-tooling-preview.version"
```

**Comment by realth000** [comment]
了解了，感谢！
