### ISSUE TITLE
在横屏状态下BottomSheetDialog不显示 / BottomSheetDialog is not displayed in landscape

### ISSUE THREAD

**Issue by Super12138** [LibChecker/LibChecker#599]
### LibChecker version / LibChecker 版本

2.3.7.950d2f67(1529)

### Bug description / Bug 描述

在横屏状态下点击应用右上角的高级菜单，打开后BottomSheetDialog不显示（只显示一点点）
In landscape, click the Advanced menu in the upper right corner of the app. When it opens, the BottomSheetDialog is not displayed (just a little bit).
![图片](https://user-images.githubusercontent.com/70494801/222132051-c589edc5-d31c-448e-8ab9-95e831640196.jpg)

### Expected behavior / 预期行为

The BottomSheetDialog is displayed

### Actual behavior / 实际行为

Not displayed

### Steps to reproduce / 复现步骤

1. 打开应用
2. 将手机横屏放置
3. 点击“高级菜单”
4. 出现上述问题

1. Open the app
6. Turn the phone in landscape
7. Tap the 'Advanced Menu'
8. View the bug

### UI / OS

HarmonyOS

### Android Version / Android 版本

10

### Additional info / 额外信息

当然，这个bug在小屏幕上也会出现（竖屏，例如手表）（这个手表的分辨率是466x466）
Of course, this bug also appears on small screens (portrait, for example: watches).(The watch's resolution is 466x466)
![图片](https://user-images.githubusercontent.com/70494801/222133805-eea5fe73-10bf-44af-9e47-557db06b79ce.png)

**Comment by qhy040404** [comment]
横屏dialog不显示老bug了
~~手表：6~~

**Comment by Super12138** [comment]
hhh
啥时候能修啊，想在手表上看看系统应用用了什么库😂
