### ISSUE TITLE
[BUG] 发现了一个奇怪的bug，应用页面搜索输入pic闪退

### ISSUE THREAD

**Issue by lvzhenbo** [LibChecker/LibChecker#601]
### LibChecker version / LibChecker 版本

2.3.7.5f8877dc

### Bug description / Bug 描述

应用页面搜索输入pic，然后闪退

### Expected behavior / 预期行为

会出现搜索结果，软件稳定运行

### Actual behavior / 实际行为

当输入到c时软件闪退

### Steps to reproduce / 复现步骤

1. 打开LibChecker，点击右上角搜索
2. 依次输入p i c

### UI / OS

MIUI 14

### Android Version / Android 版本

13

### Additional info / 额外信息

https://user-images.githubusercontent.com/32427677/222315347-6919edda-e292-4099-893b-97c3230536df.mp4

**Comment by zhaobozhen** [comment]
请提供一下 logcat 日志

**Comment by lvzhenbo** [comment]
> 请提供一下 logcat 日志

怎么拿这个日志

**Comment by qhy040404** [comment]
老bug了，复现关键词挺多的，libc也能崩
