### ISSUE TITLE
[FR] 将“备选的启动方式”与“活动”选项卡合并

### ISSUE THREAD

**Issue by lc0a** [LibChecker/LibChecker#609]
### Enhancement propose / 改进目的

对于没有桌面图标的App，在LibChecker中可以通过“备选的启动方式”来选择要启动的Activity（如图）。
![Screenshot_20230303_190812](https://user-images.githubusercontent.com/79348810/222705374-76eba94f-c7cc-4a3c-918f-00ecadee28de.png)

但对于一些具有桌面图标的App，在LibChecker中点击启动按钮后只能启动和桌面图标关联的Activity （如图），而不能再通过“备选的启动方式”来选择要启动的Activity。
![simplescreenrecorder-2023-03-03_19 20 26](https://user-images.githubusercontent.com/79348810/222707825-a684e23b-0d9e-4b3e-a296-266927e6ac1d.gif)

将“备选的启动方式”与“活动”选项卡合并后，就可以更方便地启动特定的Activity了。

### Solution / 解决方案

如图，把“备选的启动方式”可选择Activity的功能合并到“活动”选项卡中。
![Screenshot_20230303_193113_1](https://user-images.githubusercontent.com/79348810/222715062-24607083-0485-4a10-90d7-1750f969657d.png)

**Comment by qhy040404** [comment]
- LibChecker 首选的启动方式是启动 App 已定义的主 Activity，只有在 App 未定义主 Activity 时才会显示备选的启动方式。
- 只有 exported 的 Activity 才能被外部应用启动。建议用 [Anywhere-](https://github.com/zhaobozhen/Anywhere-)。
- 在活动列表中显示的 Activity 可能会被标记，如果有标记的 Activity，那启动按钮和标记会有冲突。

**Comment by su1216** [comment]
启动非主Activity与LibChecker定位关系不大，并且启动这些Activity时可能需要一些额外的参数，没有传参或者传参错误都会导致应用崩溃，所以应移除此功能 @zhaobozhen
