### ISSUE TITLE
[BUG] 2.3.9应用详情页面的UI BUG

### ISSUE THREAD

**Issue by lvzhenbo** [LibChecker/LibChecker#676]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [x] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

应用详情的TAB栏会覆盖技术图标

### Expected behavior / 预期行为

应用详情界面正常

### Actual behavior / 实际行为

应用详情界面不正常

### Steps to reproduce / 复现步骤

1. 打开LibChecker2.3.9.c2ab4dce
2. 多次点开应用详情能够复现

### UI / OS

MIUI 14

### Android Version / Android 版本

13

### Additional info / 额外信息

BUG示例
![93ae1f39b00bf0adf78f05a7ff546b5](https://user-images.githubusercontent.com/32427677/229043252-fe320645-ad38-46c3-81b3-99ef77d02e13.jpg)

**Comment by Goooler** [comment]
<img src="https://user-images.githubusercontent.com/10363352/229098196-f98fc7b0-f827-4a76-8bf4-3e1dbde71a77.png" width="33%" height="33%">
