### ISSUE TITLE
[BUG] 统计->图表页面一直加载中，重新打开以后重复加载，kotlin图表消失

### ISSUE THREAD

**Issue by realth000** [LibChecker/LibChecker#677]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

2.3.9.c2ab4dce(1586)

### Bug description / Bug 描述

底部“统计”栏里，右上角的“图表”页面：
1. 第一次打开后一直在加载中。
2. 返回统计页面，重新进入“图表页面”，等待大概一秒，会刷新页面一次，无论当前正在看哪个哪个图表（ABI Kotlin Target 和Min，都会刷）。

如下方视频所示：

https://user-images.githubusercontent.com/59462104/229251726-6116dcae-f8b4-4903-ae79-711adbe58b6f.mp4

3. 重装最新2.3.9版本，kotlin图表消失，多次重装app + 重启手机，依然消失。:cry:

![Screenshot_2023-04-01-08-02-29-549_com absinthe libchecker](https://user-images.githubusercontent.com/59462104/229254659-dedffbc2-9fd4-4365-b289-008849e099c7.jpg)

### Expected behavior / 预期行为

1. “图表”页面不会一直“加载中”。
2. “图表”页面应该只加载一次，不会重复刷新。
3. Kotlin图表可见。

### Actual behavior / 实际行为

1. “图表”页面不会一直“加载中”。
2. 进入“图表”页面后，等待一秒，会重复刷新一次。
3. 看不到kotlin图表。

### Steps to reproduce / 复现步骤

1. 打开app（最新版的2.3.9.c2ab4dce(1586)）
2. 进入第二个tab“统计”，等待进度条加载完成。
3. 点击右上角“图表”，图表页面一直显示加载中。
4. 返回“统计”页面，再次点击右上角进入“图表”，等待一秒后页面会刷新一次。

### UI / OS

MIUI

### Android Version / Android 版本

13

### Additional info / 额外信息

“图表”实际上应该已经加载完了，因为在刚看到“加载中”时马上退出，再进入，是可以看到加载好的页面。

**Comment by qhy040404** [comment]
kotlin会在数据库初始化完成后才可用

**Comment by realth000** [comment]
> kotlin会在数据库初始化完成后才可用

刚刚更新到43b3921f(1587)，重新加载了应用列表，kotlin好像不会消失了，也不会一直卡在“加载中”，但是还是有“页面刷新两次”的问题。

在进度条加载完以前打开一次图表：

https://user-images.githubusercontent.com/59462104/229275986-4a3b2ca6-797a-4c2f-822d-4c61406896f8.mp4

等待进度条加载完以后才打开图表：

https://user-images.githubusercontent.com/59462104/229276325-92c0b0f5-60d3-4f86-97ba-fdc7872c3f12.mp4

**Comment by zhaobozhen** [comment]
“页面刷新两次” 是因为后台在计算变更的应用，计算需要一定的时间，如果在你打开图表页面后才计算完，就会重新加载，这不是问题。
