### ISSUE TITLE
[BUG] 在GooglePlay下载的最新版本中，2.3.9.c2ab4dce 首次安装打开，加载之后，title栏的UI出现异常

### ISSUE THREAD

**Issue by phcbest** [LibChecker/LibChecker#682]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

在GooglePlay下载的最新版本中，2.3.9.c2ab4dce 首次安装打开，加载之后，title栏的UI出现异常，有重复
![Screenshot_2023-04-02-22-33-47-522_com absinthe l](https://user-images.githubusercontent.com/44636532/229359765-000bcffd-5880-475b-bb97-acc57a5f4ed7.jpg)

### Expected behavior / 预期行为

UI正常显示

### Actual behavior / 实际行为

UI显示异常

### Steps to reproduce / 复现步骤

首次安装或删除App数据后，第一次打开App出现该问题，在我的机型上复现率为100%

### UI / OS

miui14

### Android Version / Android 版本

13

**Comment by zhaobozhen** [comment]
最新版本已经解决了，可以在 release 下载
