### ISSUE TITLE
[BUG] 2.3.9快照有几率出现一大堆应用显示已删除

### ISSUE THREAD

**Issue by lvzhenbo** [LibChecker/LibChecker#685]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

如题，如下图，我就不截长图了，因为几乎是所有应用
![de182ff7267035993914988b8934241](https://user-images.githubusercontent.com/32427677/229726877-3d348c68-3fc3-4788-b883-da8277beceda.jpg)

### Expected behavior / 预期行为

正常显示正常的快照变更

### Actual behavior / 实际行为

出现了一大堆显示删除实际没有删除的应用

### Steps to reproduce / 复现步骤

1. 生成一个快照
2. 变更一个应用
3. 打开有几率出现这个问题

### UI / OS

MIUI 14

### Android Version / Android 版本

13

### Additional info / 额外信息

目前是2.3.9才发现，不确定之前版本有没有

**Comment by zhaobozhen** [comment]
MIUI 系统的话，检查一下系统设置里，`获取应用列表权限`是不是授予的是`仅前台使用时授予`

**Comment by lvzhenbo** [comment]
是的，仅使用中获取

**Comment by qhy040404** [comment]
保存了多少个快照啊
