### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [LibChecker/LibChecker#686]
ref: https://monitor.f-droid.org/builds/log/com.absinthe.libchecker/1587#site-footer

versionCode seems to be stuck at the same version in the APK

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/ba374c6e433435d4fe12b5b8d2596a0eec87b3b9

**Comment by zhaobozhen** [comment]
This issue was caused by a mismatch between tag commit and versionCode and has been fixed. Just wait for F-droid to recompile.

**Comment by licaon-kter** [comment]
As the links above show, it failed already and the builds are disabled.

You mean a future version that you will release soon will build ok?

**Comment by zhaobozhen** [comment]
Yes, if I release a new version, this issue can be fixed as well, but the new version will not be released soon. A faster solution would be to wait for the F-Droid repository to re-trigger the compilation of LibChecker version 2.3.9, since I have already solved the tag issue.

**Comment by licaon-kter** [comment]
Ah, I did not understand this, will test 2.3.9(1587)  locally then

**Comment by licaon-kter** [comment]
Fixed indeed, thanks https://gitlab.com/fdroid/fdroiddata/-/commit/949b0879261643d3da10b5e6287b058d6eef1e63
