### ISSUE TITLE
[BUG] 已经更新了应用,但是列表还是空

### ISSUE THREAD

**Issue by Varorbc** [LibChecker/LibChecker#709]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest CI / 最新 CI 版

### Bug description / Bug 描述

![1360efa74d4db764e9162f0b6d5ee86](https://user-images.githubusercontent.com/5714438/233263632-3abd9ad1-3782-451b-92e1-943d4ba9f248.jpg)

### Expected behavior / 预期行为

展示变更应用

### Actual behavior / 实际行为

![1360efa74d4db764e9162f0b6d5ee86](https://user-images.githubusercontent.com/5714438/233263639-6104b997-1478-4bff-8da9-3e8e8c658c17.jpg)

### UI / OS

MIUI

### Android Version / Android 版本

13

**Comment by zhaobozhen** [comment]
重新生成一张新快照试下，前几个 CI 版本可能会导致旧的快照有这个问题

**Comment by Varorbc** [comment]
好的,已经解决了,谢谢.
