### ISSUE TITLE
希望可以增加查看应用安装来源

### ISSUE THREAD

**Issue by ZWST** [LibChecker/LibChecker#739]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [x] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

![Screenshot_2023-05-07-12-18-46-92_e4fefa24eecccd406e1682398cde070b](https://user-images.githubusercontent.com/75207965/236657448-aa26e670-da95-4b2f-94ff-2d3227761890.jpg)

### Solution / 解决方案

可以考虑在图表那里增加一个应用安装来源

**Comment by qhy040404** [comment]
这个功能评估过，安卓给的公共且可用的api只能查看直接安装者，比如说某个app是从qq发起的安装请求，然后通过packageinstaller进行的安装，它会显示为packageinstaller安装的app。这样的结果就是一般用户的来源最多就是大概三个（自带应用商店，play商店和packageinstaller）因为能获得INSTALL_PACKAGES这个权限的app只能是系统应用，除非说root后
