### ISSUE TITLE
[FR] 查看dex2oat 编译方式

### ISSUE THREAD

**Issue by Doddddd** [LibChecker/LibChecker#753]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

用来判断是否需要手动优化

**Comment by zhaobozhen** [comment]
https://cs.android.com/android/platform/superproject/+/refs/heads/master:frameworks/base/services/core/java/com/android/server/pm/ComputerEngine.java;drc=7346c436e5a11ce08f6a80dcfeb8ef941ca30176;l=3215

**Comment by zhaobozhen** [comment]
https://cs.android.com/android/platform/superproject/+/refs/heads/master:frameworks/base/services/core/java/com/android/server/pm/dex/PackageDexUsage.java;drc=7346c436e5a11ce08f6a80dcfeb8ef941ca30176;l=322

**Comment by qhy040404** [comment]
> https://cs.android.com/android/platform/superproject/+/refs/heads/master:frameworks/base/services/core/java/com/android/server/pm/dex/PackageDexUsage.java;drc=7346c436e5a11ce08f6a80dcfeb8ef941ca30176;l=322

`com.android.server` is not accessible even using reflect with hiddenApiBypass

**Comment by zhaobozhen** [comment]
> > https://cs.android.com/android/platform/superproject/+/refs/heads/master:frameworks/base/services/core/java/com/android/server/pm/dex/PackageDexUsage.java;drc=7346c436e5a11ce08f6a80dcfeb8ef941ca30176;l=322
> 
> `com.android.server` is not accessible even using reflect with hiddenApiBypass

This method seems not depending on System API, can we try it?
https://cs.android.com/android/platform/superproject/+/refs/heads/master:libcore/dalvik/src/main/java/dalvik/system/DexFile.java;drc=7346c436e5a11ce08f6a80dcfeb8ef941ca30176;l=684

https://cs.android.com/android/platform/superproject/+/refs/heads/master:art/runtime/oat_file_assistant.cc;drc=7346c436e5a11ce08f6a80dcfeb8ef941ca30176;l=1254

**Comment by zhaobozhen** [comment]
https://cs.android.com/android/platform/superproject/+/master:libcore/dalvik/src/main/java/dalvik/system/DexFile.java;l=702

**Comment by qhy040404** [comment]
```kotlin
val clazz = Class.forName("dalvik.system.DexFile")
val method = clazz.getDeclaredMethod("getDexFileOptimizationStatus", String::class.java, String::class.java)
// String[] getDexFileOptimizationStatus(String fileName, String instructionSet)
// fileName base.apk
// instructionSet arm64, arm, x86, x86_64, riscv64
// primaryCpuAbi
method.isAccessible = true
method.invoke(null, packageInfo.applicationInfo.sourceDir, "arm64"))
```
