### ISSUE TITLE
[FR] More Icons [AWS IVS player, EXPO]

### ISSUE THREAD

**Issue by Ppang0405** [LibChecker/LibChecker#794]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

I want to report some libraries and new icons.

1. libexpo-modules-core.so, it's the Expo umbrella library for Expo's related React Native libraries.
<img title="expo" src="https://github.com/LibChecker/LibChecker/assets/33455900/d28ea1dc-1669-4de1-8574-ce0db3b8baff" width=600>
I forget their trademark icons link, did google and found these icons.
<img title="expo_icon_1" src="https://github.com/LibChecker/LibChecker/assets/33455900/9b53e9bd-7ee5-4129-8d7c-fca12e566ee0" width=600>
<img title="expo_icon_2" src="https://github.com/LibChecker/LibChecker/assets/33455900/9ddfbff8-c21c-45f6-9b88-bebee5c1a364" width=600>
<img title="expo_icon_3" src="https://github.com/LibChecker/LibChecker/assets/33455900/adf2c591-c465-40dd-b46b-602c70bb3be2" width=600>

2. libplayercore.so, it's an AWS IVS player, Idk any icons for this. https://github.com/aws/amazon-ivs-react-native-player
https://github.com/aws-samples/amazon-ivs-player-android-sample/blob/master/README.md
<img title="expo_icon_3" src="https://github.com/LibChecker/LibChecker/assets/33455900/8399af3b-ad4e-4172-8f20-59eae37dbc1e" width=600>

3. libhermes_executor.so, this one should be marked as Hermes but Idk why it's not.
<img title="expo_icon_3" src="https://github.com/LibChecker/LibChecker/assets/33455900/753433e7-4d71-41bf-98b0-09f217be7c5b" width=600>

4. libexpo-av.so, It's a Expo library: https://docs.expo.dev/versions/latest/sdk/av/ we can use Expo icon for this as well.
<img title="expo_icon_3" src="https://github.com/LibChecker/LibChecker/assets/33455900/a09b99e7-575c-4ecd-8686-d1ed53233e58" width=600>

**Comment by qhy040404** [comment]
Submit new rules [here](https://github.com/LibChecker/LibChecker-Rules/issues)
