### ISSUE TITLE
[FR] Should show "Preinstalled app" if timestamp equals zero

### ISSUE THREAD

**Issue by zhaobozhen** [LibChecker/LibChecker#802]
https://github.com/LibChecker/LibChecker/blob/20b9bb5cb1b5bdaa1b038b6ed2171ef13cd16a6e/app/src/main/kotlin/com/absinthe/libchecker/recyclerview/adapter/snapshot/SnapshotAdapter.kt#L205

**Comment by qhy040404** [comment]
1230768000000
