### ISSUE TITLE
[FR] 应用权限清单给出具体详情

### ISSUE THREAD

**Issue by Hakuin123** [LibChecker/LibChecker#852]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

形如android.permission.XXX等的权限名查看起来较为不便

根据https://developer.android.google.com给出的对照文档，将权限名与其具体内容对应，方便查看

**Comment by su1216** [comment]
PermissionInfo.loadDescription @zhaobozhen
