### ISSUE TITLE
虚拟导航栏问题

### ISSUE THREAD

**Issue by chenjunyu19** [LibChecker/LibChecker#86]
列表的底部没有给虚拟导航栏留空，导致列表最后一项被遮挡以至于无法点击。

LibChecker 2.1.1.04c3da3(770)
EMUI 9.1.0
Android 9

![Screenshot_20210711_192925_com absinthe libchecker](https://user-images.githubusercontent.com/15167799/125194140-9f3af880-e282-11eb-9dfa-86287ea3feb2.jpg)

**Comment by zhaobozhen** [comment]
奇怪，所有界面都是这样吗？我在我的手机上开启了虚拟导航栏没发现有问题，不知道是不是系统原因。

**Comment by zhaobozhen** [comment]
试了一下 harmony OS，确实有此问题，应该是华为魔改了系统导致，我想想怎么兼容吧。

**Comment by chenjunyu19** [comment]
暂时只发现应用详情这个活动有问题，像首页那种大卡片、设置页那种标准列表都没有问题。

**Comment by cyb233** [comment]
> 试了一下 harmony OS，确实有此问题，应该是华为魔改了系统导致，我想想怎么兼容吧。

vivo
OriginOS 1.0
Android 10
同样复现此问题

**Comment by chenjunyu19** [comment]
快照的差异比较活动也有问题。

2.1.3.a0268509(811)

![Screenshot_20210725_215333_com absinthe libchecker](https://user-images.githubusercontent.com/15167799/126901936-959ef6e0-344a-4a68-8cd1-a7a08aa58732.jpg)

**Comment by zhaobozhen** [comment]
76a7546f93500d5651977fc9a1f7e613c6259aea 已解决。
