### ISSUE TITLE
res目录下的资源文件如何混淆成一些  a b c d 这种文件名字的

### ISSUE THREAD

**Issue by shichuanenhui** [LibChecker/LibChecker#868]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

res目录下的资源文件如何混淆成一些  a b c d 这种文件名字的，代码中什么地方设置才会混淆成a b c d这种名字的，并且把一些目录文件都移动到res根目录下了？

**Comment by zhaobozhen** [comment]
参考 https://github.com/LibChecker/LibChecker/blob/master/build-logic/src/main/kotlin/ResoptPlugin.kt
另外此类提问可以移至 Discussion 区，请不要提交到 issue
