### ISSUE TITLE
libzlib.so原生库错误显示

### ISSUE THREAD

**Issue by binx6** [LibChecker/LibChecker#881]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

版本为2.4.2，在扫描原生库的时候发现的这个bug，libzlib.so不知道为什么被归类于libzip.so，这两压根不是一个东西
![IMG_20230810_122431](https://github.com/LibChecker/LibChecker/assets/123862842/ae0cdd3a-1056-43a5-9736-9cf427968689)

### Expected behavior / 预期行为

误导他人

### Actual behavior / 实际行为

None

### Steps to reproduce / 复现步骤

1.规则仓库：github（好像是）
2.找一个带libzlib.so的应用，如AndLua+
3.原生库

### UI / OS

MIUI

### Android Version / Android 版本

11

### Additional info / 额外信息

libzlib.so的官方Website: http://www.zlib.net

**Comment by qhy040404** [comment]
zlib一般对应的不是libz.so嘛

**Comment by zhaobozhen** [comment]
https://github.com/nih-at/libzip/blob/ecb4043db21718f5d19b80701bd1e693e566775a/lib/CMakeLists.txt#L5 这个确实标注有误

**Comment by binx6** [comment]
> zlib一般对应的不是libz.so嘛 

**反正是那位名叫d1y的规则贡献者的失误**

**Comment by binx6** [comment]
> https://github.com/nih-at/libzip/blob/ecb4043db21718f5d19b80701bd1e693e566775a/lib/CMakeLists.txt#L5 这个确实标注有误

`希望作者大大能抽空审批Issues以及更新一下规则仓库`

**Comment by yfdyh000** [comment]
> 这两压根不是一个东西

libzip有依赖zlib组件，但生成的so似乎不会那样命名。
https://github.com/nih-at/libzip/issues/217

**Comment by binx6** [comment]
> https://github.com/nih-at/libzip/blob/ecb4043db21718f5d19b80701bd1e693e566775a/lib/CMakeLists.txt#L5 这个确实标注有误

有个疑问，规则库更新后，似乎外部卡片中的标签文字没有得到更新？![IMG_20230815_110407.jpg](https://github.com/LibChecker/LibChecker/assets/123862842/49d8b83c-9b25-46ef-8136-752f644164f2)

**Comment by zhaobozhen** [comment]
规则标签是本地的，需要更新依赖库，CI 版本已经更新
