### ISSUE TITLE
libcjson.so原生库错误显示

### ISSUE THREAD

**Issue by binx6** [LibChecker/LibChecker#889]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

这位兄弟的操作真是十分下饭呵，不知道他是怎么想的，bug原因参考上次反馈的，别的不废话了，如图所示
![IMG_20230814_192243](https://github.com/LibChecker/LibChecker/assets/123862842/c526d240-2bc6-4941-88a3-bd6a848c5b96)

### Expected behavior / 预期行为

八竿子打不着调，误导他人

### Actual behavior / 实际行为

有点欺诈用户的意味，令人堪忧

### Steps to reproduce / 复现步骤

1.找一个cJSON处理过的应用，如AndLua+

### UI / OS

MIUI

### Android Version / Android 版本

11

### Additional info / 额外信息

安装过cJSON才会出现libcjson.so，这跟bson扯不到一起，不是同组库，此外我怀疑这位名叫`d1y`的规则贡献者是否贡献的其它内容可能还会出现这种问题？？？

这是cJSON：https://github.com/DaveGamble/cJSON

**Comment by binx6** [comment]
@zhaobozhen

**Comment by zhaobozhen** [comment]
已更正，感谢反馈。
