### ISSUE TITLE
[FR] 能否添加导出apk的功能

### ISSUE THREAD

**Issue by DearZack** [LibChecker/LibChecker#898]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

导出apk

### Solution / 解决方案

PackageInfo.applicationInfo.sourceDir 目录下的apk

### Additional info / 额外信息

PackageInfo.applicationInfo.sourceDir 目录下的apk

**Comment by qhy040404** [comment]
#358 

- [ ] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。
