### ISSUE TITLE
[FR] 列表里是否可以一键过滤掉系统应用

### ISSUE THREAD

**Issue by DearZack** [LibChecker/LibChecker#899]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

列表里是否可以一键过滤掉系统应用？
查看统计时，系统应用会有一些干扰

**Comment by qhy040404** [comment]
应用列表的高级菜单会同时控制统计中的数据，在高级菜单里把显示系统应用取消掉就可以了
