### ISSUE TITLE
libffmpegkit.so原生库错误显示

### ISSUE THREAD

**Issue by binx6** [LibChecker/LibChecker#910]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest CI / 最新 CI 版

### Bug description / Bug 描述

如图：
![IMG_20230903_203208](https://github.com/LibChecker/LibChecker/assets/123862842/fa922cc5-979c-49e2-ac1a-b2a7503dbd82)
此外libffmpegkit.so和libffmpegkit_abidetect.so是同组库

### Expected behavior / 预期行为

不明确，[FFmpeg](https://github.com/FFmpeg/FFmpeg)中是没有kit的

### Actual behavior / 实际行为

None

### Steps to reproduce / 复现步骤

1. 扫描1DM+这个应用的原生库，即可

### UI / OS

MIUI

### Android Version / Android 版本

11

### Additional info / 额外信息

可以看看这个作为参考：[here](https://github.com/arthenica/ffmpeg-kit/tree/main/android/ffmpeg-kit-android-lib/src/main/cpp) 。同组库我已提交到Rules的issue里

**Comment by qhy040404** [comment]
[Submit rule bug here](https://github.com/LibChecker/LibChecker-Rules/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=%5BBug%5D+%28Library+label%29)
