### ISSUE TITLE
[BUG] 安装intent而来的包分析应用属性信息错误

### ISSUE THREAD

**Issue by zjns** [LibChecker/LibChecker#929]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

如题所述。

### Expected behavior / 预期行为

显示安装intent而来的包应用属性。

### Actual behavior / 实际行为

系统已安装包的应用属性。
![Screenshot_20230924_172552_LibChecker](https://github.com/LibChecker/LibChecker/assets/10793522/73d328dc-9ca2-4f11-8e3d-236b9c4f8191)

![Screenshot_20230924_172558_LibChecker](https://github.com/LibChecker/LibChecker/assets/10793522/f014c677-ce8c-4131-81c4-f393c3a14ea5)

上图中系统安装的哔哩哔哩版本为7.46.0，正在分析的安装包版本为7.49.0。应用属性应该展示7.49.0版本的，而不是7.46.0版本的。

### UI / OS

OneUI

### Android Version / Android 版本

13

**Comment by qhy040404** [comment]
Already fixed by 11125e80

**Comment by zjns** [comment]
![Screenshot_20230924_180703_LibChecker](https://github.com/LibChecker/LibChecker/assets/10793522/c4dd4397-b42c-4bce-8571-73ead9ef868e)
这里的大小计算也不对吧，这里用的应该是千进制算的，通常不应该用1024进制吗？实际大小是114.93M，而不是121M。

**Comment by qhy040404** [comment]
这个问题就从来没有统一过，谁管他到底怎么算

**Comment by zjns** [comment]
至少大部分操作系统的文件管理器是按照1024进制算的，除了macOS。
