### ISSUE TITLE
[功能请求] 固定底部导航栏

### ISSUE THREAD

**Issue by Jesse205** [LibChecker/LibChecker#960]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。

### Enhancement propose / 改进目的

1. 使用户非常方便地切换页面，不再需要向上滑动调出低栏这个额外操作

### Solution / 解决方案

固定底部导航栏，滑动时候不可收起

**Comment by zhaobozhen** [comment]
之前设计滑动时隐藏底栏，是因为在小屏设备或手机横屏状态下，底栏占据很大比例的屏幕空间，导致体验不佳。而我又不想在应用中加入太多的设置开关来控制各种 feature。目前的方案只需要通过滑动列表即可控制底栏的显示状态，是我能想到最便捷的方案了。

**Comment by Jesse205** [comment]
我觉得小屏手机最好使用Material2，因为使用Material2可以省出很多空间，一劳永逸。现在MaterialComponent里面仍然保留了Material2，可以用上。

实现起来也不难，所有不同的值性写到主题的attr里面就可以了。默认的属性就已经可以满足很多效果了。

如果要用的话，可以在设置里面加一个风格切换菜单，方便用户在不同的风格之间切换

**Comment by zhaobozhen** [comment]
> 我觉得小屏手机最好使用Material2，因为使用Material2可以省出很多空间，一劳永逸。现在MaterialComponent里面仍然保留了Material2，可以用上。
> 
> 实现起来也不难，所有不同的值性写到主题的attr里面就可以了。默认的属性就已经可以满足很多效果了。
> 
> 
> 
> 如果要用的话，可以在设置里面加一个风格切换菜单，方便用户在不同的风格之间切换

以前是有 md2 和 md3 切换的，但实际上 LC 并没有完全遵循 MD 设计，有很多 UX 是我自己设计的，因此不能简单地通过修改 attr 切换风格，也就是每次加入新的 UI 后都要考虑两套主题的 UI 设计。后来由于造成了很多额外的工作，加上 md3 已经是主流的设计趋势，就去掉了 md2 的支持。

**Comment by Jesse205** [comment]
我发现你的代码里面很多地方都是动态生成view，因此修改的时候没有任何东西可以参考（比如预览等），极易修改错误。你指的额外工作是这个吗？
如果是的话，我可以协助你完成迁移到xml。

对于UI设计的话，可以以MD3为主，MD2有bug的时候再修。

**Comment by zhaobozhen** [comment]
> 我发现你的代码里面很多地方都是动态生成view，因此修改的时候没有任何东西可以参考（比如预览等），极易修改错误。你指的额外工作是这个吗？
> 如果是的话，我可以协助你完成迁移到xml。
> 
> 对于UI设计的话，可以以MD3为主，MD2有bug的时候再修。

是指很多 view 没有直接使用 md 现成的组件，而是自己写的，导致切换主题风格也要维护两套，而不是简单改几个属性就完成了。很多应用 md2/md3 切换的功能都出现在 UI 迁移的过渡期（包括 LC），而我不太想让应用里的开关越来越多，所以应该不会同时维护两个主题。

**Comment by Jesse205** [comment]
好吧

**Comment by Jesse205** [comment]
或者，只在屏幕高度小于一定值的时候开启滚动隐藏，如果大于一定值的话禁用滚动隐藏？这样会不会更好一些

**Comment by zhaobozhen** [comment]
可以使用高度占用百分比来判断（如高度小于屏幕高度的1/7这种），这样就可以适应不同分辨率或屏幕密度下的差异性。
